### ISSUE TITLE
Some problems during installation

### ISSUE THREAD

**Issue by speedinghzl** [zhanghang1989/PyTorch-Encoding#10]
Hi @zhanghang1989, thanks for your sharing!  When installing the Encoding package, I encounter some problems and solve these problems.
1. thc_encoding.h: No such file or directory #8 
the thc_encoding.h is stored in encoding/kernel, so I just add include path in [build.py](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/build.py#L45)
`os.path.join(this_file,'encoding/src/'),
os.path.join(this_file,'encoding/kernel/')]`

2. THCDeviceTensor.cuh: No such file or directory
`git clone https://github.com/zhanghang1989/PyTorch-Encoding
& git checkout v0.2.0`.  
I switch pytorch branch from master to v0.2, because in master branch, there is no such file.

3. SyntaxError: invalid syntax in File "/home/hzl/anaconda2/lib/python2.7/site-packages/encoding/parallel.py", line 232
`return (modules[0](*inputs[0], *targets[0], **kwargs_tup[0]), )`
I just remove *before inputs[0]

4. test fail in test_dilated_avgpool
$$ I just ignore it.

 Finally, I want to use the synchronized BatchNorm, could you please provide some example code to show how to use it?
Thanks again!

**Comment by zhanghang1989** [comment]
Thanks for providing the compiling steps @speedinghzl ! I will make it easier to use the code in future version. Currently, I am working on a conference deadline, so I don't have time to provide an example. But I will definitely release the example code after the conference submission together with arXiv report. 

The code is not hard to read, and it has some comments. If you would like it to use it immediately, I will suggest spending some time to go through it.

**Comment by speedinghzl** [comment]
Thanks for your help! I notice that the syncBN needs input with tuple or list type. And, you mention that each module in the network should be in self-parallel mode in [parallel.py](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/parallel.py#L194). Could you please give some instructions and advice to achieve that. Thanks again.

**Comment by zhanghang1989** [comment]
See the new commit https://github.com/zhanghang1989/PyTorch-Encoding/commit/c92a7c2422af69b4b0f920b379533319d7bb6f0f

**Comment by sukhad-app** [comment]
I face exactly same issues. Cant resolve them even after the commit too. Please provide some fix.

**Comment by zhanghang1989** [comment]
Please use python3. Let me know if you still have the problem. Thx
