### ISSUE TITLE
how to train encnet on cityscape dataset 

### ISSUE THREAD

**Issue by gjm441** [zhanghang1989/PyTorch-Encoding#118]
Hi zhanghang, great work for sharing.
I have trained VOCAug dataset and then finetune on VOC dataset, get mIOU 0.8506 on val. Have you provided coco pretrained encnet model in modelzoo?And how to train encnet on cityscape dataset? 
I hope you  can give some suggestions,thanks

**Comment by zhanghang1989** [comment]
Hi, I haven't tried EncNet on Cityscapes dataset. I expect you may need to enlarge the crop size to fix the high resolution setting in that dataset (probably crop_size = 768).

**Comment by zhanghang1989** [comment]
Will do. I will let you know when it is ready.
