### ISSUE TITLE
 No module named 'encoding._ext.encoding_lib._encoding_lib'

### ISSUE THREAD

**Issue by kimchicanh** [zhanghang1989/PyTorch-Encoding#12]
HI,

I try to run your project. I can run it with terminal, however when I try to debug with pycharm, it lack of lib:

Traceback (most recent call last):
  File "/media/code/PyTorch-Encoding/experiments/main.py", line 23, in <module>
    from encoding.utils import *
  File "/media/code/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    import encoding.nn
  File "/media/code/PyTorch-Encoding/encoding/nn/__init__.py", line 11, in <module>
    from .syncbn import *
  File "/media/code/PyTorch-Encoding/encoding/nn/syncbn.py", line 23, in <module>
    from ..functions import view_each, multi_each, sum_each, batchnormtrain, batchnormeval, sum_square 
  File "/media/code/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/media/code/PyTorch-Encoding/encoding/functions/encoding.py", line 16, in <module>
    from .._ext import encoding_lib
  File "/media/code/PyTorch-Encoding/encoding/_ext/encoding_lib/__init__.py", line 3, in <module>
    from ._encoding_lib import lib as _lib, ffi as _ffi
ImportError: No module named 'encoding._ext.encoding_lib._encoding_lib'

In folder encoding_lib do not have _encoding_lib but when I run with terminal it still can run. Maybe you will know the reason. Please help me.

Thanks

**Comment by zhanghang1989** [comment]
I guess you are importing the package in the project folder. Just go to another folder

**Comment by zhanghang1989** [comment]
Please do a `git pull` and install again. Let me know if you still have the problem. Thx

**Comment by zhanghang1989** [comment]
I think you are using python2. This package requires python3.

**Comment by kimchicanh** [comment]
Thank for your support, I will be back with your project and install it again, now, I am a little bit busy.
Once, I can debug with pycharm if I copy encoding lib (after build project) in python 3,5 to project.

**Comment by kimchicanh** [comment]
One question, In lua project (Deep encoding), you load train, test and validation but in python project, you just load train and test, it mean I have to change the file name when train ( test -> valid) and when test (valid->test) ???. It is my concern, pleases answer me :v
Thank you

**Comment by zhanghang1989** [comment]
See the docs here: http://hangzh.com/PyTorch-Encoding/experiments/texture.html

**Comment by jind11** [comment]
I failed installing encoding package in my python2 env and I encountered errors like "return (modules[0](*inputs[0], *targets[0], **kwargs_tup[0]), )
                                   ^
SyntaxError: invalid syntax".
In order to install it successfully, must I use python 3? Thanks!

**Comment by zhanghang1989** [comment]
Yes, that’s the problem of using python2.
