### ISSUE TITLE
Docs for Updated Encoding Method

### ISSUE THREAD

**Issue by panfengli** [zhanghang1989/PyTorch-Encoding#129]
Hi Hang Zhang,

I notice that you have update your method for encoding, where you seems add a normalization term `STD`, I am wondering when will the documents for the new encoding functions available. 

Thank you!

**Comment by zhanghang1989** [comment]
Hi @panfengli ,

That is for an on-going work. I haven't provided any python API for this method yet.  Only the C++ code is accidentally released. I will provide the python API and documentation when I have more experimental results and probably arXiv paper for reference.

**Comment by panfengli** [comment]
Ok, I got it.
