### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by xiaopingzeng** [zhanghang1989/PyTorch-Encoding#135]
I use "pip install torch-encoding" to install, and I use the method of https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.W8oFpvkzaUl to install the ninja. But still get an error "ninja: build stopped: subcommand failed" when I import encoding. Could you tell me how to do? thanks

**Comment by zhanghang1989** [comment]
Please install `ninja` by following the steps here https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.W8oUgBNKjOB

**Comment by zhanghang1989** [comment]
Please use PyTorch 1.0, select the `preview` version instead of `stable` https://pytorch.org/get-started/locally/
