### ISSUE TITLE
'NoneType' object has no attribute 'run_slave'

### ISSUE THREAD

**Issue by DavieHR** [zhanghang1989/PyTorch-Encoding#137]
i just use your synchronize-batchnorm module. batchsize is 8, gpu num is 4. 
thx.

**Comment by zhanghang1989** [comment]
did you use compatible [DataParallelModel](https://hangzhang.org/PyTorch-Encoding/parallel.html#encoding.parallel.DataParallelModel)

**Comment by DavieHR** [comment]
@zhanghang1989  emmm. i use it. But, i encounter anther problem,  
_, warp_image = warpnet(d_image_color, ref_image_color)
The warpnet Module return a tuple.
After using DataParalleModel
ValueError: too many values to unpack (expected 2)

**Comment by zhanghang1989** [comment]
Please use `DataParallelModel` together with `DataParallelCriterion` to handle multiple outputs

**Comment by DavieHR** [comment]
@winwinJJiang Nope....

**Comment by winwinJJiang** [comment]
@zhanghang1989  航哥v587！ 搞定了！
