### ISSUE TITLE
libTHC.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by iliadsouti** [zhanghang1989/PyTorch-Encoding#14]
Hi,
I installed the pytorch from source but it can not find libTHC.so.1. However, it is in my virtual env since I checked with locate. /home/ubuntu/pyramid/lib/python2.7/site-packages/torch/lib/libTHC.so.1
It seems that libTHC.so.1 is missing.

running install_scripts
Traceback (most recent call last):
  File "test/test.py", line 11, in <module>
    import encoding
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/__init__.py", line 13, in <module>
    import encoding.nn
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/nn/__init__.py", line 11, in <module>
    from .syncbn import *
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/nn/syncbn.py", line 23, in <module>
    from ..functions import view_each, multi_each, sum_each, batchnormtrain, batchnormeval, sum_square 
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/functions/encoding.py", line 16, in <module>
    from .._ext import encoding_lib
  File "/home/ubuntu/pyramid/local/lib/python2.7/site-packages/encoding/_ext/encoding_lib/__init__.py", line 3, in <module>
    from ._encoding_lib import lib as _lib, ffi as _ffi
ImportError: libTHC.so.1: cannot open shared object file: No such file or directory

**Comment by zhanghang1989** [comment]
Try compiling this package again. You need to reinstall this package after reinstall PyTorch

**Comment by iliadsouti** [comment]
I tried to recompile it. But the encoding.h not found happend. I traced the error and it was because libTHC.so.1 and libTH.so.1 were not found in anaconda2/lib/site-packages/torch/lib. I copied them from some place else to this folder. It gets compiled but when it tries to run test.py it gets to the above error. Can you help me out. Where is the location of ._encoding_lib exactly?

**Comment by zhanghang1989** [comment]
I have just update a version. Can you do a `git pull` and install it again? let me know if you still have the problem.

**Comment by zhanghang1989** [comment]
This package requires python3

**Comment by iliadsouti** [comment]
It didn't work with git pull with python 2.7. I would have to try with python 3.

**Comment by iliadsouti** [comment]
With python 3 now I get this error.
-- Build files have been written to: /home/ubuntu/projects/PyTorch-Encoding/encoding/lib
[ 50%] Building NVCC (Device) object CMakeFiles/ENCODING.dir/kernel/ENCODING_generated_thc_encoding.cu.o
Scanning dependencies of target ENCODING
**make[2]: *** No rule to make target '/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1', needed by 'libENCODING.so'.  Stop.**
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ENCODING.dir/all' failed
make[1]: *** [CMakeFiles/ENCODING.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iliadsouti** [comment]
I copied libTHC.so.1 from someplace else. Now it is installed without an error. I should make a test.
Thanks!

**Comment by zhanghang1989** [comment]
Hi,
The `THC` library was renamed to `ATen` in PyTorch, which cause the problem. Thx for pointing out. It is fixed in https://github.com/zhanghang1989/PyTorch-Encoding/commit/d9d7b1f07fe9ee479ee9891617eadb6ac3fac3b2
