### ISSUE TITLE
import encoding error

### ISSUE THREAD

**Issue by elward-cjy** [zhanghang1989/PyTorch-Encoding#141]
hi航哥 你好，我想要跑TEN网络，然后按照步骤安装了pytorch master分支源码（1.0的也试过）还有 encoding，以及ninja-1.8.2，但是还是报错 Error building extension 'enclib_gpu'，具体错误如下，可以麻烦你有空帮忙看看吗？非常感谢
cuda-9.0 ;
cudnn7.0.5 ;
![image](https://user-images.githubusercontent.com/39157940/47707445-c84c0400-dc66-11e8-9f79-afc7fb66f3d9.png)

**Comment by elward-cjy** [comment]
不好意思啊，我自己找到问题了，是cuda的路径有点问题，打扰你了，谢谢大佬的开源~，

**Comment by zilongzhong** [comment]
@elward-cjy Correct. We need to change the CUDA environment path to kill this bug.
For example, 
export CUDA_HOME='/usr/local/cuda/'
export CUDA_HOME='/usr/local/cuda-9.0/'

**Comment by OilGao** [comment]
@zilongzhong  请问 你现在能跑最新版本的 encoding吗 能提供一下 您的环境吗

**Comment by OilGao** [comment]
@elward-cjy 请问一下 你现在能跑最新版本的 encoding吗 能提供一下 您的环境吗

**Comment by zilongzhong** [comment]
I used the preview version of pytorch1.0 and torchvision as follows:

pytorch-nightly           1.0.0.dev20181102 py3.7_cuda9.0.176_cudnn7.1.2_0
torch-encoding            0.5.2                     <pip>
torchvision-nightly       0.2.1                      py_0    fastai

**Comment by Lydia-z** [comment]
@elward-cjy 想问一下你提到的pytorch的分支源码是什么意思呢，看其他问题下面也提到了要用Pytorch master

**Comment by elward-cjy** [comment]
> @elward-cjy 想问一下你提到的pytorch的分支源码是什么意思呢，看其他问题下面也提到了要用Pytorch master

就是因为encoding的代码作者有空的时候会根据pytorch版本的更新，同步做了更新，方便后面的人使用，所以你要么自己改源码，要么跟作者使用的pytorch版本一致，我之前是pytorch1.0还没出来的时候用的，版本不稳定，最新的是pytorch github master分支上的源码
