### ISSUE TITLE
pytorch and Python vision

### ISSUE THREAD

**Issue by yyangmei** [zhanghang1989/PyTorch-Encoding#147]
Which vision of pytorch and python does the code work? My pytorch 0.4.1 and python 3.6 can work or not? Thanks!

**Comment by zhanghang1989** [comment]
Please use the preview PyTorch 1.0

**Comment by CS-Jackson** [comment]
Hi, @zhanghang1989 . Can I use this package based on the stable pytorch 1.0 ?

**Comment by zhanghang1989** [comment]
Will do by this weekend. Thanks for pointing out the stable 1.0.

**Comment by wangxiaodong1021** [comment]
hello, which pytorch branch is compatible?
