### ISSUE TITLE
Test module failed 

### ISSUE THREAD

**Issue by lmycross** [zhanghang1989/PyTorch-Encoding#159]
I installed the pytorch 1.0 stable and updated to the latest version, however the result of test_module in your project was "failed (errors=1, failures=2)". 
My environment is python 3.5, cuda 9.2, tested on 6 gpus.

**Comment by zhanghang1989** [comment]
Which line does it fail?

**Comment by lmycross** [comment]
Sorry for replying late, I have solved the problems.
