### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extension

### ISSUE THREAD

**Issue by lilingge** [zhanghang1989/PyTorch-Encoding#167]
Hi,author. I have followed the instructions on your page.  I got your code by git clone, and run "python setup.py install" with no errors. However when I run "python3 demo.py", I got the error like this:

Traceback (most recent call last):
  File "/home/llg/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 873, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 2, in <module>
    import encoding
  File "/home/llg/Documents/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/llg/Documents/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/llg/Documents/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/llg/Documents/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/llg/Documents/PyTorch-Encoding/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/llg/Documents/PyTorch-Encoding/encoding/lib/__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/llg/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/llg/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/llg/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 837, in _write_ninja_file_and_build
    verify_ninja_availability()
  File "/home/llg/.local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 875, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extension

How to overcome it?  What's the "Ninja"?

**Comment by zhanghang1989** [comment]
Please run following command:
```bash
wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
sudo unzip ninja-linux.zip -d /usr/local/bin/
sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
```
solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB

**Comment by EmmaSRH** [comment]
Hi,author. Does the solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB work? I tried it and it still doesn't work.

**Comment by lilingge** [comment]
> Hi,author. Does the solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB work? I tried it and it still doesn't work.

Hi, my problem was solved.However, the code still can't run. I tried many times, even ask an engineer of Dji for help.  Finally, my personal opinion is that the stability of the code is poor.  I hope you can run it successfully and let me know.  Thanks

**Comment by nemonameless** [comment]
> Please run following command:
> 
> ```shell
> wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
> sudo unzip ninja-linux.zip -d /usr/local/bin/
> sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
> ```
> 
> solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB

How to do this without sudo Permission?

**Comment by SysOverdrive** [comment]
I seem to have the same problem 

Traceback (most recent call last):
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    'build_ext': BuildExtension
  File "\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

How can I fix this on a windows machine ?

**Comment by lianghouhao** [comment]
> > Please run following command:
> > ```shell
> > wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
> > sudo unzip ninja-linux.zip -d /usr/local/bin/
> > sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
> > ```
> > 
> > 
> > solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB
> 
> How to do this without sudo Permission?

Just curious. Have you found a method to overcome this sudo permission issue? thanks

**Comment by BooPatienze** [comment]
> > Please run following command:
> > ```shell
> > wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
> > sudo unzip ninja-linux.zip -d /usr/local/bin/
> > sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
> > ```
> > 
> > 
> > solution from https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.XEDUk89KjOB
> 
> How to do this without sudo Permission?

I  just `pip install ninja`, and then no problem.

**Comment by woctezuma** [comment]
The simplest solution is sometimes overlooked. Thank you, BooPatienze!

**Comment by csyhy1986** [comment]
> I seem to have the same problem
> 
> Traceback (most recent call last):
> Traceback (most recent call last):
> File "setup.py", line 26, in
> 'build_ext': BuildExtension
> File "\lib\site-packages\setuptools__init__.py", line 144, in setup
> return distutils.core.setup(**attrs)
> File "\lib\distutils\core.py", line 148, in setup
> dist.run_commands()
> File "\lib\distutils\dist.py", line 966, in run_commands
> self.run_command(cmd)
> File "\lib\distutils\dist.py", line 985, in run_command
> cmd_obj.run()
> File "\lib\site-packages\setuptools\command\install.py", line 67, in run
> self.do_egg_install()
> File "\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
> self.run_command('bdist_egg')
> File "\lib\distutils\cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "\lib\distutils\dist.py", line 985, in run_command
> cmd_obj.run()
> File "\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
> cmd = self.call_command('install_lib', warn_dir=0)
> File "\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
> self.run_command(cmdname)
> File "\lib\distutils\cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "\lib\distutils\dist.py", line 985, in run_command
> cmd_obj.run()
> File "\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
> self.build()
> File "\lib\distutils\command\install_lib.py", line 107, in build
> self.run_command('build_ext')
> File "\lib\distutils\cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "\lib\distutils\dist.py", line 985, in run_command
> cmd_obj.run()
> File "\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
> _build_ext.run(self)
> File "\lib\distutils\command\build_ext.py", line 340, in run
> self.build_extensions()
> File "\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
> build_ext.build_extensions(self)
> File "\lib\distutils\command\build_ext.py", line 449, in build_extensions
> self._build_extensions_serial()
> File "\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
> self.build_extension(ext)
> File "\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
> _build_ext.build_extension(self, ext)
> File "\lib\distutils\command\build_ext.py", line 534, in build_extension
> depends=ext.depends)
> File "\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
> with_cuda=with_cuda)
> File "\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
> error_prefix='Error compiling objects for extension')
> File "\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
> raise RuntimeError(message)
> RuntimeError: Error compiling objects for extension
> 
> How can I fix this on a windows machine ?

I also encounter with this problem on a windows platform, have you solved it bro?

**Comment by zhanghang1989** [comment]
For Windows, I would recommend using docker https://hangzhang.org/PyTorch-Encoding/notes/compile.html#using-docker

**Comment by tommy-qichang** [comment]
I found the subprocess does not include the lib path of conda environments. So I manually set the environments in the script, and it works now.
eg.

```
my_env = os.environ.copy()
my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
os.environ.update(my_env)
```

**Comment by nom57** [comment]
None of these solutions work for me on Windows

**Comment by RenzeLou** [comment]
> I found the subprocess does not include the lib path of conda environments. So I manually set the environments in the script, and it works now. eg.
> 
> ```
> my_env = os.environ.copy()
> my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
> os.environ.update(my_env)
> ```

Thanks. It works for me!

**Comment by liyiersan** [comment]
> my_env = os.environ.copy()
> my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
> os.environ.update(my_env)

I met the same problem on windows, have you ever solved?

**Comment by liyiersan** [comment]
> > I seem to have the same problem
> > Traceback (most recent call last):
> > Traceback (most recent call last):
> > File "setup.py", line 26, in
> > 'build_ext': BuildExtension
> > File "\lib\site-packages\setuptools__init__.py", line 144, in setup
> > return distutils.core.setup(**attrs)
> > File "\lib\distutils\core.py", line 148, in setup
> > dist.run_commands()
> > File "\lib\distutils\dist.py", line 966, in run_commands
> > self.run_command(cmd)
> > File "\lib\distutils\dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "\lib\site-packages\setuptools\command\install.py", line 67, in run
> > self.do_egg_install()
> > File "\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
> > self.run_command('bdist_egg')
> > File "\lib\distutils\cmd.py", line 313, in run_command
> > self.distribution.run_command(command)
> > File "\lib\distutils\dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
> > cmd = self.call_command('install_lib', warn_dir=0)
> > File "\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
> > self.run_command(cmdname)
> > File "\lib\distutils\cmd.py", line 313, in run_command
> > self.distribution.run_command(command)
> > File "\lib\distutils\dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
> > self.build()
> > File "\lib\distutils\command\install_lib.py", line 107, in build
> > self.run_command('build_ext')
> > File "\lib\distutils\cmd.py", line 313, in run_command
> > self.distribution.run_command(command)
> > File "\lib\distutils\dist.py", line 985, in run_command
> > cmd_obj.run()
> > File "\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
> > _build_ext.run(self)
> > File "\lib\distutils\command\build_ext.py", line 340, in run
> > self.build_extensions()
> > File "\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
> > build_ext.build_extensions(self)
> > File "\lib\distutils\command\build_ext.py", line 449, in build_extensions
> > self._build_extensions_serial()
> > File "\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
> > self.build_extension(ext)
> > File "\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
> > _build_ext.build_extension(self, ext)
> > File "\lib\distutils\command\build_ext.py", line 534, in build_extension
> > depends=ext.depends)
> > File "\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
> > with_cuda=with_cuda)
> > File "\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
> > error_prefix='Error compiling objects for extension')
> > File "\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
> > raise RuntimeError(message)
> > RuntimeError: Error compiling objects for extension
> > How can I fix this on a windows machine ?
> 
> I also encounter with this problem on a windows platform, have you solved it bro?
Same problem on windows, did you solve it?

**Comment by zhanghang1989** [comment]
Please use the docker solution if you ran into any troubles especially on windows https://hangzhang.org/PyTorch-Encoding/notes/compile.html#using-docker

**Comment by adityamwagh** [comment]
@nom57 A bit off topic, but you might want to use [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) if you are on Windows. It greatly simplifies working with a machine learning workload on Windows. 

I use it regularly on Windows 11. It's essentially a virtual machine, although with near native performance.

**Comment by AndyJZhao** [comment]
> I found the subprocess does not include the lib path of conda environments. So I manually set the environments in the script, and it works now. eg.
> 
> ```
> my_env = os.environ.copy()
> my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
> os.environ.update(my_env)
> ```

Just a few comments on the great answer of [tommy-qichang](https://github.com/tommy-qichang) which solves my problem immediately.
1. The code could be a little bit simpler, as below:
```
conda_path = "/path/to/your/conda/envs/py3/bin"
os.environ['PATH'] = f'{conda_path}:{os.environ["PATH"]}'
```
2. The code should be placed **BEFORE GPU related packages are imported**. In other words, there shouldn't be any torch/tensorflow/transformers packages before you've set the environment variables correctly.

**Comment by Ren-Ma** [comment]
> 

This solution is the real answer to this question! Thank you @tommy-qichang @AndyJZhao ！

> > I found the subprocess does not include the lib path of conda environments. So I manually set the environments in the script, and it works now. eg.
> > ```
> > my_env = os.environ.copy()
> > my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
> > os.environ.update(my_env)
> > ```
> 
> Just a few comments on the great answer of [tommy-qichang](https://github.com/tommy-qichang) which solves my problem immediately.
> 
> 1. The code could be a little bit simpler, as below:
> 
> ```
> conda_path = "/path/to/your/conda/envs/py3/bin"
> os.environ['PATH'] = f'{conda_path}:{os.environ["PATH"]}'
> ```
> 
> 2. The code should be placed **BEFORE GPU related packages are imported**. In other words, there shouldn't be any torch/tensorflow/transformers packages before you've set the environment variables correctly.

**Comment by fengchuanpeng** [comment]
my_env = os.environ.copy()
my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
os.environ.update(my_env)
Hello, which folder should these codes be placed in?

**Comment by fengchuanpeng** [comment]
my_env = os.environ.copy()
my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
os.environ.update(my_env)
@Ren-Ma   Hello, which folder should these codes be placed in?

**Comment by isrishtisingh** [comment]
> For Windows, I would recommend using docker https://hangzhang.org/PyTorch-Encoding/notes/compile.html#using-docker

@SysOverdrive and @csyhy1986 I also encountered this issue on my Windows system, doing the following steps has solved the issue for me.

1. Visit the URL: https://github.com/ninja-build/ninja/releases
2. Download the zip file named "ninja-win.zip"
3. Extract the file content from zip, and you will see a .exe file named ninja or ninja-win
4. Copy and paste the path of this file in your Windows environment path (both in user and system variables path)
5. Now restart your application/VS Code or whatever.

I am not sure if this is the right solution, but my error is gone now.

**Comment by y455293511** [comment]
> my_env = os.environ.copy()
> my_env["PATH"] = "/path/to.your/conda/.conda/envs/py3/bin:" + my_env["PATH"]
> os.environ.update(my_env)

Its work!
