### ISSUE TITLE
it seems like the  sync-batchnorm (in syncbn_kernel.cu) can't match the pytorch1.0.0 ?

### ISSUE THREAD

**Issue by cqq0505** [zhanghang1989/PyTorch-Encoding#168]
When I try to train or test the model , it seems like code in " syncbn_kernel.cu" can't match the pytorch1.0.0 :(I've  installed the cuda9.2, ninja1.8, pytorch1.0.0)
the errors  of train mode look like that:
RuntimeError: cudaGetLastError() == cudaSuccess ASSERT FAILED at /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu:424, please report a bug to PyTorch. (**Expectation_Forward_CUDA** at /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu:424)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fa21f2a3cc5 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: Expectation_Forward_CUDA(at::Tensor) + 0x281 (0x7fa2133b2c86 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #2: <unknown function> + 0x8a6b5 (0x7fa21338b6b5 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #3: <unknown function> + 0x838f6 (0x7fa2133848f6 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #4: <unknown function> + 0x7c181 (0x7fa21337d181 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #5: <unknown function> + 0x7c2ed (0x7fa21337d2ed in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #6: <unknown function> + 0x69872 (0x7fa21336a872 in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
<omitting python frames>
frame #15: THPFunction_apply(_object*, _object*) + 0x5dd (0x7fa24f73c40d in /home/qingqing/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

**Comment by huanghoujing** [comment]
@cqq0505 I find it necessary to (1) install pytorch 1.0 from source and (2) modify some include clauses of Pytorch-Encoding. My installation guide is [this](https://github.com/huanghoujing/PyTorch-Encoding/blob/master/Install_Prerequisite_for_Pytorch_Encoding.md) and then [this](https://github.com/huanghoujing/PyTorch-Encoding/blob/master/Fix_Bugs_of_Pytorch_Encoding.md).

**Comment by d-li14** [comment]
Thanks for @huanghoujing 's suggestion, but I wonder what the real cause is. It will be hard to find the clues from a totally new installation process. Indeed, I have been successfully installed torch-encoding on two servers but met the aforementioned issue in a machine with Tesla M40 GPU, kept almost the same software configurations.

**Comment by huanghoujing** [comment]
@d-li14 Would [this post](https://discuss.pytorch.org/t/warning-for-old-gpu-and-cuda-runtime-error-with-fast-ai-lesson/13868/7?u=houjing_huang) solve your problem? It says that when installing pytorch from source, we have to install with compatibility for various CUDA architectures.

**Comment by d-li14** [comment]
@huanghoujing Sorry for the late reply, I just tried to install pytorch through building from source code and kept all other steps unchanged. The errors no longer exist now.

**Comment by zhanghang1989** [comment]
It works with PyTorch 1.0.0, but not 1.0.1

**Comment by qiulesun** [comment]
@zhanghang1989 Does this repo works with PyTorch 1.1 ?

**Comment by yinjunbo** [comment]
@zhanghang1989 @qiulesun Same question. Can this be used in PyTorch 1.1 now?

**Comment by zhanghang1989** [comment]
I am not maintaining the code any more, because I have moved to MXNet development. 
I believe both PyTorch and MXNet have built-in syncbatchnorm now.
