### ISSUE TITLE
2 Questions of parallel.py

### ISSUE THREAD

**Issue by lck1201** [zhanghang1989/PyTorch-Encoding#175]
Hi, thanks for your contribution. I am using a old version of your library and have several questions.

In the latest version, you have abandon this line of code. Why? And what was its function in the old version?
https://github.com/zhanghang1989/PyTorch-Encoding/blob/16363650d07c8efb6fcb602570b360b2f6e1f710/encoding/parallel.py#L101

Why do you comment this line? To my understanding, the function is the same with line 135. And in the latest version, you delete this line.
https://github.com/zhanghang1989/PyTorch-Encoding/blob/16363650d07c8efb6fcb602570b360b2f6e1f710/encoding/parallel.py#L136

**Comment by zhanghang1989** [comment]
The new syncbn implementation does not need to call back.
Delete a comment won’t affect anything.

**Comment by lck1201** [comment]
Sorry, I didn't make myself clear.

1. Do these two lines of code(if L136 not commented) have the same function, i.e. gather tensors from multiple GPUs?
2. If yes, why do you choose L135 instead of L136?
https://github.com/zhanghang1989/PyTorch-Encoding/blob/16363650d07c8efb6fcb602570b360b2f6e1f710/encoding/parallel.py#L135
https://github.com/zhanghang1989/PyTorch-Encoding/blob/16363650d07c8efb6fcb602570b360b2f6e1f710/encoding/parallel.py#L136

**Comment by zhanghang1989** [comment]
After a certain version of pytorch, it no longer allows gathering single element tensors.

**Comment by lck1201** [comment]
Ok, I get it. Thanks a lot!
