### ISSUE TITLE
License???

### ISSUE THREAD

**Issue by hrieke** [zhanghang1989/PyTorch-Encoding#182]
Hi,

You state that the license is the MIT License, but then you go and have below it the BSD 3-clause text.
So which one is it?

Thanks!

**Comment by zhanghang1989** [comment]
Keeping the LICENCE file when redistributing it should be find.

**Comment by hrieke** [comment]
So you can see the differences:
MIT License
https://opensource.org/licenses/MIT

BSD 3-clause License 
https://opensource.org/licenses/BSD-3-Clause

Your license file says:
MIT License
and then goes to show the BSD 3-clause license.

Do you mean that the license is: 
- only the MIT License, 
- only the BSD 3-clause, 
- either the MIT LIcense OR the BSD 3-clause license, 
- both the MIT License AND the BSD 3-clause license at the same time?

Thanks!

**Comment by zhanghang1989** [comment]
Thanks for the reply!

I will update the LICENCE file to standard MIT format. Re-distributing the package with the MIT License is fine.
