### ISSUE TITLE
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by charlesCXK** [zhanghang1989/PyTorch-Encoding#187]
Hi,
Thanks for your great work and sharing.
During using the `torch-encoding` package, I meet the following question:
```
anaconda3/envs/pytorch1.0/lib/python3.7/site-packages/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```
Could you tell me what caused this problem? Thank you very much !

I installed the `torch-encoding` package by pip and here is my system information:

- OS: Ubuntu 16.04
- PyTorch: 1.0.1
- CUDA: 9.0
- GCC: 5.3.0

**Comment by zhanghang1989** [comment]
Could you try to remove that file? It should be automatically generated again.

**Comment by charlesCXK** [comment]
@zhanghang1989 
I try to remove that .so file, and run `import encoding`.
The same error occurred.

**Comment by zhanghang1989** [comment]
Could you try to use CUDA 10.0 and reinstall PyTorch for CUDA 10.0, then reinstall torch-encoding.

**Comment by charlesCXK** [comment]
Thanks for your reply, I will try it later.

**Comment by charlesCXK** [comment]
It is sovled by install PyTorch=1.0.0

**Comment by XRSWATER** [comment]
> It is sovled by install PyTorch=1.0.0

Hi, I have the same problem. Would you mind sharing your experience in installing pytorch 1.0.0? I can't find instructions for Pytorch1.0.0 installation on the official website. I can only install pytorch1.0.1.  I have the same system as you.

**Comment by gitunit** [comment]
> > It is sovled by install PyTorch=1.0.0
> 
> Hi, I have the same problem. Would you mind sharing your experience in installing pytorch 1.0.0? I can't find instructions for Pytorch1.0.0 installation on the official website. I can only install pytorch1.0.1. I have the same system as you.

see here how to install version 1.0.0
https://pytorch.org/get-started/previous-versions/#v100
