### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by XRSWATER** [zhanghang1989/PyTorch-Encoding#195]
I use the command: 
`CUDA_VISIBLE_DEVICES=0python train.py --dataset ade20k --se-loss --aux --batch-size 2 --lr 0.01 --model encnet`

then I get the issues:

> /home/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py:2421: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
>   warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
> Traceback (most recent call last):
>   File "train.py", line 184, in <module>
>     trainer.training(epoch)
>   File "train.py", line 115, in training
>     loss = self.criterion(outputs, target)
>   File "/home/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/PyTorch-Encoding/experiments/segmentation/encoding/parallel.py", line 86, in forward
>     return self.module(inputs, *targets[0], **kwargs[0])
>   File "/home/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/PyTorch-Encoding/experiments/segmentation/encoding/nn/loss.py", line 36, in forward
>     pred1, se_pred, pred2, target = tuple(inputs)
> **ValueError: not enough values to unpack (expected 4, got 2)**

Can someone teach me how to solve the problem?

python3.6
Pytorch1.0.0
l

**Comment by 1829805046** [comment]
hello，@XRSWATER ，I also have this problem. Can you teach me how to solve it? Thanks.

**Comment by XRSWATER** [comment]
Hello, 
Maybe my solution can't work for you.
I use the author's latest codes, and then the problem gets solved.
But what doubtful is that when I ran the program in my another computer, it had the same problem at first, after 3 days, it can run this program though I change nothing.



------------------ 原始邮件 ------------------
发件人: "1829805046"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 下午4:00
收件人: "zhanghang1989/PyTorch-Encoding"<PyTorch-Encoding@noreply.github.com>;
抄送: "十二象"<513221837@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [zhanghang1989/PyTorch-Encoding] ValueError: not enough values tounpack (expected 4, got 2) (#195)




hello，@XRSWATER ，I also have this problem. Can you teach me how to solve it? Thanks.

**Comment by 1829805046** [comment]
@XRSWATER Thank you for your reply.

**Comment by Chenfeng1271** [comment]
It  is ok when I train the encnet with `CUDA_VISIBLE_DEVICES=0,1 python experiments/segmentation/train.py --dataset ADE20K --model EncNet --aux --se-loss --backbone resnet50 --base-size 640 --crop-size 576  --batch-size 2`

However when I replace the model with deeplab, it raise the same error `ValueError: not enough values to unpack (expected 4, got 3)` Can u jive me some hints  for solving that?

**Comment by Chenfeng1271** [comment]
I just handle this problem in another way. I use the debug of vs code and set the lauch.json. It is OK for EncNet training but inapplicable for fcn, pspnet, deeplab. When I try to use the default command in the terminal, it's well addressed.

**Comment by neverstoplearn** [comment]
> I just handle this problem in another way. I use the debug of vs code and set the lauch.json. It is OK for EncNet training but inapplicable for fcn, pspnet, deeplab. When I try to use the default command in the terminal, it's well addressed.

hi  can you teach how to change it to run in one GPU? thanks.

**Comment by LeslieZhoa** [comment]
> It is ok when I train the encnet with `CUDA_VISIBLE_DEVICES=0,1 python experiments/segmentation/train.py --dataset ADE20K --model EncNet --aux --se-loss --backbone resnet50 --base-size 640 --crop-size 576 --batch-size 2`
> 
> However when I replace the model with deeplab, it raise the same error `ValueError: not enough values to unpack (expected 4, got 3)` Can u jive me some hints for solving that?

Maybe replace `loss = self.criterion(outputs, target)` with `loss = self.criterion(*outputs, target)` can help

**Comment by zhanghang1989** [comment]
> It is ok when I train the encnet with `CUDA_VISIBLE_DEVICES=0,1 python experiments/segmentation/train.py --dataset ADE20K --model EncNet --aux --se-loss --backbone resnet50 --base-size 640 --crop-size 576 --batch-size 2`
> 
> However when I replace the model with deeplab, it raise the same error `ValueError: not enough values to unpack (expected 4, got 3)` Can u jive me some hints for solving that?

You should remove `--se-loss`, which is only available for EncNet

**Comment by zhanghang1989** [comment]
> > I just handle this problem in another way. I use the debug of vs code and set the lauch.json. It is OK for EncNet training but inapplicable for fcn, pspnet, deeplab. When I try to use the default command in the terminal, it's well addressed.
> 
> hi can you teach how to change it to run in one GPU? thanks.

Use `train_dist.py` should have no issue on 1 gpu
