### ISSUE TITLE
Runtime error：include enclib_gpu and ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by celabi** [zhanghang1989/PyTorch-Encoding#203]
Since I tried in conda to use:
ubuntu 16.04
pytorch-nightly=1.0.0  dev20190328
torch-encoding=0.5.2
cuda=10 
cudnn=7.3
ninja 
but the python prepare_minc.py still response lots of errors.
could some one open your environment ?

RuntimeError: Error building extension 'enclib_gpu': b'[1/7] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/d/.local/lib/python3.6/site-packages/torch/include -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/d/.conda/envs/pytorch-enconding/include/....... return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());\n                                            ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n simple_collector<policy> collect_arguments(Args &&...args) {\n ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note:   template argument deduction/substitution failed:\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n unpacking_collector<policy> collect_arguments(Args &&...args) {\n ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\nninja: build stopped: subcommand failed.\n'

**Comment by celabi** [comment]
RuntimeError: Error building extension 'enclib_gpu': b'[1/7] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/d/.local/lib/python3.6/site-packages/torch/include -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/d/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/d/.conda/envs/pytorch-enconding/include/....... return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());\n                                            ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n simple_collector<policy> collect_arguments(Args &&...args) {\n ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note:   template argument deduction/substitution failed:\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n unpacking_collector<policy> collect_arguments(Args &&...args) {\n ^\n/home/d/.local/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\nninja: build stopped: subcommand failed.\n'

**Comment by tjulyz** [comment]
Have you solved your problem? I meet the same one.

**Comment by krishnakanthnakka** [comment]
I have faced the same problem. Please help us know the solution to this.

**Comment by tjulyz** [comment]
> I have faced the same problem. Please help us know the solution to this.

Could you try this one for installation? https://github.com/tjulyz/PyTorch-Encoding

**Comment by weixia1** [comment]
> > I have faced the same problem. Please help us know the solution to this.
> 
> Could you try this one for installation? https://github.com/tjulyz/PyTorch-Encoding

good
