### ISSUE TITLE
Can i train the encnet by using only one Titan V?

### ISSUE THREAD

**Issue by diegorafaellucio** [zhanghang1989/PyTorch-Encoding#205]
I am trying to train the encnet on my own dataset, however, the bellow message is presented:

ValueError: not enough values to unpack (expected 4, got 2)

I search a solution on the issues, but don't found anything.

I am using the bellow command to train:

sudo python3 /home/diego/Doutorado/frameworks/encnet/experiments/segmentation/train.py --dataset ubiris500 --model EncNet --aux --se-loss

**Comment by neverstoplearn** [comment]
i have mmet the same question as you ,have you solve it? thanks.

**Comment by zhanghang1989** [comment]
Using https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/train_dist.py should solve this problem. I am close it. Feel free to reopen if error exists.
