### ISSUE TITLE
Error when q try to train in only one GPU?

### ISSUE THREAD

**Issue by diegorafaellucio** [zhanghang1989/PyTorch-Encoding#210]
Can i train a model by using only one GPU? @zhanghang1989

**Comment by StacyYang** [comment]
If using single gpu , change it to normal BN

**Comment by diegorafaellucio** [comment]
How I can do it?

**Comment by zhanghang1989** [comment]
Replace the `SyncBatchNorm` with `BatchNorm` should fix the problem

**Comment by diegorafaellucio** [comment]
@zhanghang1989 

I try to use the:

from torch.nn import BatchNorm3d
from torch.nn import BatchNorm2d
from torch.nn import BatchNorm1d

however, the error 'ValueError: not enough values to unpack (expected 4, got 2)' persists 

Can you tell me which is the correct batch normalization class?

**Comment by zhenmafan7** [comment]
> @zhanghang1989
> 
> I try to use the following changes in train.py:
> 
> **1o**
> 
> from torch.nn import BatchNorm1d
> 
> however, the error 'ValueError: expected 2D or 3D input (got 4D input)' persists
> 
> **2o**
> 
> from torch.nn import BatchNorm2d
> 
> however, the error 'ValueError: expected 4D input (got 3D input)' persists
> 
> **3o **
> 
> from torch.nn import BatchNorm3d
> 
> however, the error 'ValueError: expected 5D input (got 5D input)' persists
> 
> I am using the following command:
> python train.py --dataset pcontext --model encnet --aux --se-loss
> 
> Can you tell me which is the correct batch normalization class?


hi,I've had the same problem, did you solve it?

**Comment by zhenmafan7** [comment]
> If using single gpu , change it to normal BN

Hi,I am sorry to bother you,I change the code as follows:
1.from torch.nn impot batchnorm2d
2.replace norm_layer = BatchNorm2d with norm_layer = SyncBatchNorm (train.py)
However, there are still some problems:
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    trainer.training(epoch)
  File "train.py", line 111, in training
    loss = self.criterion(outputs, target)
  File "/home/wq/.conda/envs/p3t1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/.conda/envs/p3t1/lib/python3.6/site-packages/encoding/parallel.py", line 130, in forward
    return self.module(inputs, *targets[0], **kwargs[0])
  File "/home/wq/.conda/envs/p3t1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/.conda/envs/p3t1/lib/python3.6/site-packages/encoding/nn/loss.py", line 36, in forward
    pred1, se_pred, pred2, target = tuple(inputs)
ValueError: not enough values to unpack (expected 4, got 2)

could you please give me some advices to slove this problem?

**Comment by neverstoplearn** [comment]
I have meet the same error  have you solve it  thanks

**Comment by zhanghang1989** [comment]
Using https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/train_dist.py should solve this problem. I am close it. Feel free to reopen if error exists.
