### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by tycallen** [zhanghang1989/PyTorch-Encoding#216]
Found a typo when I read the docs, in the [How the BN works](https://hangzhang.org/PyTorch-Encoding/notes/syncbn.html)
![image](https://user-images.githubusercontent.com/3022000/61860264-4094dc80-aefc-11e9-9a67-a5ad1f2f1750.png)

**Comment by zhanghang1989** [comment]
Thanks for the feedback. The typo is fixed in latest doc https://hangzhang.org/PyTorch-Encoding/tutorials/syncbn.html
