### ISSUE TITLE
Cityscapes dataset

### ISSUE THREAD

**Issue by yiqing427** [zhanghang1989/PyTorch-Encoding#223]
Hi, may I ask is there a prepare_cityscapes.py file for preparation of Cityscapes dataset since I only find cityscapes.py? Thank you very much.

**Comment by zhanghang1989** [comment]
Please see the scripts here:
https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/scripts/prepare_citys.py

**Comment by gtgtgt1117** [comment]
> Please see the scripts here:
> https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/scripts/prepare_citys.py


嗨,这个数据集也是无法下载的
