### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by shehabk** [zhanghang1989/PyTorch-Encoding#226]
I am trying to run recognition on `cifar10` as outlined in [docs](https://hangzhang.org/PyTorch-Encoding/experiments/cifar.html). But I am receiving value error. Following is the command I ran.

```
python main.py --dataset cifar10 --model encnetdrop --widen 8 --ncodes 32 --lr-scheduler cos --epochs 600 --checkname mycheckpoint```
```
I checked and found that encdrop is infact not in [model_zoo.py](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/models/model_zoo.py)

**Comment by zhanghang1989** [comment]
Please see the model here https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/recognition/model/encnetdrop.py

**Comment by shehabk** [comment]
Thanks @zhanghang1989, I think encnetdrop model was not added in the model zoo when the code was updated. My quick fix for running was to update the main.py in recognition to match with some previous commit.

```
    try:
        model = encoding.models.get_model(args.model, pretrained=args.pretrained)
    except ValueError:
        models = importlib.import_module('model.'+args.model)
        model = models.Net(args)
```
