### ISSUE TITLE
download link missing

### ISSUE THREAD

**Issue by InstantWindy** [zhanghang1989/PyTorch-Encoding#227]
Hi. This download link https://hangzh.s3.amazonaws.com/encoding/data/coco/train_ids.pth was missing. Where  can I get this? Thanks.

**Comment by zhanghang1989** [comment]
That's okay if the file is missing. It will be automatically generated for the first time, just take some time.

**Comment by InstantWindy** [comment]
you mean the code can generate "train_ids.pth" file ?

**Comment by zhanghang1989** [comment]
Yes. Just start the training.

**Comment by InstantWindy** [comment]
Thanks.
