### ISSUE TITLE
Is it compatiable with pytorch 1.1.0?

### ISSUE THREAD

**Issue by shyanguan** [zhanghang1989/PyTorch-Encoding#232]
My enviornment:
Ubuntu 16.04
CUDA 9.0
CUDNN 7.5
g++-4.8 
gcc-4.8
pytorch-1.1.0

**Comment by mehameha998** [comment]
I try to install this repo, but some errors happened, which seems haven't been mentioned before.

A clip of error:
/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:74: note: candidates are:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n simple_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note:   template argument deduction/substitution failed:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n unpacking_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h: In instantiation of \'int pybind11::cast(pybind11::object&&) [with T = std::basic_string<char>]\':\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:1717:85:   required from \'T pybind11::object::cast() && [with T = std::basic_string<char>]\'\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/detail/class.h:537:138:   required from here\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:1713:24: error: cannot convert \'std::basic_string<char>\' to \'int\' in return\n     return cast<T>(object);\n                        ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h: In instantiation of \'pybind11::object pybind11::detail::object_api<Derived>::operator()(Args&& ...) const [with pybind11::return_value_policy policy = (pybind11::return_value_policy)1u; Args = {pybind11::handle&, pybind11::handle&}; Derived = pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr>]\':\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:923:27:   required from \'pybind11::str pybind11::str::format(Args&& ...) const [with Args = {pybind11::handle&, pybind11::handle&}]\'\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/pybind11.h:755:72:   required from here\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:74: error: no matching function for call to \'collect_arguments(pybind11::handle&, pybind11::handle&)\'\n     return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());\n                                                                          ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:74: note: candidates are:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n simple_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note:   template argument deduction/substitution failed:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n unpacking_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h: In instantiation of \'pybind11::object pybind11::detail::object_api<Derived>::operator()(Args&& ...) const [with pybind11::return_value_policy policy = (pybind11::return_value_policy)1u; Args = {pybind11::object&, const pybind11::handle&}; Derived = pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr>]\':\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/pytypes.h:923:27:   required from \'pybind11::str pybind11::str::format(Args&& ...) const [with Args = {pybind11::object&, const pybind11::handle&}]\'\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/pybind11.h:1401:51:   required from here\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:74: error: no matching function for call to \'collect_arguments(pybind11::object&, const pybind11::handle&)\'\n     return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());\n                                                                          ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:74: note: candidates are:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n simple_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2087:1: note:   template argument deduction/substitution failed:\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)\n unpacking_collector<policy> collect_arguments(Args &&...args) {\n ^\n/data/home/eneraldliu/anaconda3/envs/gsy/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2094:1: note:   template argument deduction/substitution failed:\nninja: build stopped: subcommand failed.\n'

**Comment by mehameha998** [comment]
It's really hard to install in some special enviorment..... I was stucked in this error about two days.

**Comment by voodoopotato** [comment]
It is not compatible. You will need to install with pytorch 1.0.0

**Comment by dreamPoet** [comment]
I meet the same problem...however nvlab's model GSCNN said it used pytorch1.1.0 with encoding.. I am confused.

**Comment by zhanghang1989** [comment]
The master branch should be compatible with PyTorch 1.4.0.
