### ISSUE TITLE
Issue with loading pretrained models code

### ISSUE THREAD

**Issue by ashwath98** [zhanghang1989/PyTorch-Encoding#243]
My PyTorch version is 1.0.1 and Cuda is 10, I am testing your work on the google collab environment

When I run this code
`model = encoding.models.get_model('encnet_resnet50_pcontext', pretrained=True).cuda()`

I get the following error

Pretrained model for encnet_resnet50_<module 'encoding.datasets.pcontext' from '/usr/local/lib/python3.6/dist-packages/encoding/datasets/pcontext.py'> is not available

Which occurs at this point  in the models/model_store.py 
```
 def short_hash(name):
    if name not in _model_sha1:
        raise ValueError('Pretrained model for {name} is not available.'.format(name=name))
    return _model_sha1[name][:8]
 
```

And is probably due to this line of code  from the models/encnet.py in the get_encnet function

`model.load_state_dict(torch.load( get_model_file('encnet_%s_%s'%(backbone, acronyms[dataset]), root=root)))`

for some reason the acronyms[dataset] value is returning a reference to the pcontext dataset which is <module 'encoding.datasets.pcontext' from '/usr/local/lib/python3.6/dist-packages/encoding/datasets/pcontext.py'>

I've checked the datasets module in the repo and the acronyms dictionary seems to have only string values, but despite that, the above error is occurring.

What do you think is the possible cause? I've installed the library through pip, is that version, not the updated one?

**Comment by Hu01001** [comment]
I am having the same issue. Were you able to solve it? Thanks!

**Comment by ashwath98** [comment]
Yeah. Clone and Install the Library
git clone https://github.com/zhanghang1989/PyTorch-Encoding
%cd PyTorch-Encoding/
python setup.py install

**Comment by zhanghang1989** [comment]
This should be resolved in the newest version. Feel free to reopen if error still exists.
