### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Hu01001** [zhanghang1989/PyTorch-Encoding#245]
I followed the instruction below:
git clone https://github.com/zhanghang1989/PyTorch-Encoding && cd PyTorch-Encoding
python setup.py install
but got the error.It will always  be blocked when importing encoding.I don't know why about it.

[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import encoding

For a long time after that, nothing appeared and no error was reported

**Comment by zhanghang1989** [comment]
When using the package for the first time, it compiles the binary files automatically. Therefore, it will take a few minutes. If the version is compatible, you should be able to import the package.

**Comment by Hu01001** [comment]
OK，Thanks.Finally I downloaded it again and it works.
