### ISSUE TITLE
Error with import with pytorch 1.4

### ISSUE THREAD

**Issue by Shiro-LK** [zhanghang1989/PyTorch-Encoding#247]
Hi,

Thank you for your repository.

I got a similar issue to this one : https://github.com/zhanghang1989/PyTorch-Encoding/issues/219

but I am using cuda 10.1, pytorch 1.4 and ubuntu 18.04, ninja 1.8.2 

I am wondering if someone succeeded to make this repo working with a similar configuration to mine ?
In fact, in the repo, it seems there was a commit for pytorch 1.4 but as I do not succeed to make it worked, I am wondering if it is compatible.

**Comment by zhanghang1989** [comment]
I just updated the repo recently.

I have not problem running with CUDA 10, pytorch 1.4 and ubuntu 16.04 on AWS DL AMI.

**Comment by zhanghang1989** [comment]
FYI, the new version should be compatible with pytorch 1.6 https://github.com/zhanghang1989/PyTorch-Encoding/pull/309
