### ISSUE TITLE
c99 flag error

### ISSUE THREAD

**Issue by lfz** [zhanghang1989/PyTorch-Encoding#25]
Hi Zhang Hang, thank you for your effort and releasing this code.

I have insalled pytorch from source and use python 3.5 (anaconda3). When I run python setup.py install I got the following error:

> creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding                                                                                [3/1814]
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding/encoding
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding/encoding/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../
../lib/include -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/
ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/lib/include -I/data/home/liao/Downloads/PyTorch-Encoding/
encoding/kernel -I/data/home/liao/Downloads/PyTorch-Encoding/encoding/kernel/include -I/data/home/liao/Downloads/PyTorch-Encoding/encoding/src/ -I/home/liao/anaconda3
/include/python3.5m -c build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/encoding._ext
.encoding_lib._encoding_lib.o
In file included from /home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THVector.h:5:0,
                 from /home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:12,
                 from build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.c:433:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_digamma’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:139:3: error: ‘for’ loop initial declarations are only allowed in C99 o
r C11 mode
   for (int i = 0; i < 4; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:139:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to
 compile your code
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_digammaf’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:154:3: error: ‘for’ loop initial declarations are only allowed in C99 o
r C11 mode
   for (int i = 0; i < 4; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:172:3: error: ‘for’ loop initial declarations are only allowed in C99 o
r C11 mode
   for (int i = 0; i < 6; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:190:3: error: ‘for’ loop initial declarations are only allowed in C99 o
r C11 mode
   for (int i = 0; i < 6; ++i) {

error: command 'gcc' failed with exit status 1

I know that I should add -std=c99 somewhere but I don't know where to add. I have tried to modify the CmakeLists.txt
` 48 SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c99")
`
but it still does not work

Could you help me solving this? Thank you

**Comment by lfz** [comment]
> liao@img14:~/Downloads/PyTorch-Encoding$ python setup.py install                                                                                            [103/1822]
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Checking if C linker supports --verbose - yes
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Checking if CXX linker supports --verbose
-- Checking if CXX linker supports --verbose - yes
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TORCH_BUILD_DIR: /home/liao/anaconda3/lib/python3.5/site-packages/torch/lib
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5") 
-- Autodetected CUDA architecture(s): 5.2 5.2 5.2 5.2 5.2 5.2 5.2 5.2
-- Torch_INSTALL_INCLUDE:/home/liao/anaconda3/lib/python3.5/site-packages/torch/lib/include/home/liao/anaconda3/lib/python3.5/site-packages/torch/lib/include/TH/home/
liao/anaconda3/lib/python3.5/site-packages/torch/lib/include/THC
-- Configuring done                                                                                                                                                                                              [49/1743]
-- Generating done
-- Build files have been written to: /home/liao/Downloads/PyTorch-Encoding/encoding/lib
[ 50%] Building NVCC (Device) object CMakeFiles/ENCODING.dir/kernel/ENCODING_generated_thc_encoding.cu.o
Scanning dependencies of target ENCODING
[100%] Linking CXX shared library libENCODING.so
[100%] Built target ENCODING
running install
-- Building version 0.1.0+01946d4
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/encoding
copying encoding/parallel.py -> build/lib.linux-x86_64-3.5/encoding
copying encoding/syncbn.py -> build/lib.linux-x86_64-3.5/encoding
copying encoding/version.py -> build/lib.linux-x86_64-3.5/encoding
copying encoding/utils.py -> build/lib.linux-x86_64-3.5/encoding
copying encoding/__init__.py -> build/lib.linux-x86_64-3.5/encoding
creating build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/basic.py -> build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/customize.py -> build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/syncbn.py -> build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/encoding.py -> build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/aggregate.py -> build/lib.linux-x86_64-3.5/encoding/functions
copying encoding/functions/__init__.py -> build/lib.linux-x86_64-3.5/encoding/functions
creating build/lib.linux-x86_64-3.5/encoding/modules
copying encoding/modules/encoding.py -> build/lib.linux-x86_64-3.5/encoding/modules
copying encoding/modules/__init__.py -> build/lib.linux-x86_64-3.5/encoding/modules
creating build/lib.linux-x86_64-3.5/encoding/dilated
copying encoding/dilated/densenet.py -> build/lib.linux-x86_64-3.5/encoding/dilated
copying encoding/dilated/resnet.py -> build/lib.linux-x86_64-3.5/encoding/dilated
copying encoding/dilated/__init__.py -> build/lib.linux-x86_64-3.5/encoding/dilated
creating build/lib.linux-x86_64-3.5/encoding/nn
copying encoding/nn/basic.py -> build/lib.linux-x86_64-3.5/encoding/nn
copying encoding/nn/customize.py -> build/lib.linux-x86_64-3.5/encoding/nn
copying encoding/nn/syncbn.py -> build/lib.linux-x86_64-3.5/encoding/nn
copying encoding/nn/encoding.py -> build/lib.linux-x86_64-3.5/encoding/nn
copying encoding/nn/__init__.py -> build/lib.linux-x86_64-3.5/encoding/nn
creating build/lib.linux-x86_64-3.5/encoding/lib
copying encoding/lib/libENCODING.so -> build/lib.linux-x86_64-3.5/encoding/lib
creating build/lib.linux-x86_64-3.5/encoding/kernel
copying encoding/kernel/common.h -> build/lib.linux-x86_64-3.5/encoding/kernel
copying encoding/kernel/thc_encoding.h -> build/lib.linux-x86_64-3.5/encoding/kernel
creating build/lib.linux-x86_64-3.5/encoding/kernel/generic
copying encoding/kernel/generic/device_tensor.h -> build/lib.linux-x86_64-3.5/encoding/kernel/generic
copying encoding/kernel/generic/pooling_kernel.h -> build/lib.linux-x86_64-3.5/encoding/kernel/generic
copying encoding/kernel/generic/syncbn_kernel.h -> build/lib.linux-x86_64-3.5/encoding/kernel/generic
copying encoding/kernel/generic/encoding_kernel.h -> build/lib.linux-x86_64-3.5/encoding/kernel/generic
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.c'
creating build/temp.linux-x86_64-3.5
building 'encoding._ext.encoding_lib._encoding_lib' extension
creating build/temp.linux-x86_64-3.5/build
creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/data
creating build/temp.linux-x86_64-3.5/data/home
creating build/temp.linux-x86_64-3.5/data/home/liao
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding/encoding
creating build/temp.linux-x86_64-3.5/data/home/liao/Downloads/PyTorch-Encoding/encoding/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/liao/anaconda3/lib/python3.5/
site-packages/torch/utils/ffi/../../lib/include/TH -I/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/liao/anaconda3/lib/python3.5/site-packages/t
orch/lib/include -I/data/home/liao/Downloads/PyTorch-Encoding/encoding/kernel -I/data/home/liao/Downloads/PyTorch-Encoding/encoding/kernel/include -I/data/home/liao/Downloads/PyTorch-Encoding/encoding/src/ -I/home/liao
/anaconda3/include/python3.5m -c build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.o
In file included from /home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THVector.h:5:0,
                 from /home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:12,
                 from build/temp.linux-x86_64-3.5/encoding._ext.encoding_lib._encoding_lib.c:433:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_digamma’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:139:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < 4; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:139:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_digammaf’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:154:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < 4; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:172:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < 6; ++i) {
   ^
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/home/liao/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:190:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i = 0; i < 6; ++i) {
   ^
error: command 'gcc' failed with exit status 1

**Comment by lfz** [comment]
I solve this by:

export CXXFLAGS="-std=c++11"                                                                           
export CFLAGS="-std=c99"

**Comment by zhanghang1989** [comment]
Thanks for providing the solution! This will be addressed in next release.
