### ISSUE TITLE
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.

### ISSUE THREAD

**Issue by Leslie0115** [zhanghang1989/PyTorch-Encoding#267]
Hi, I encountered the following problem as title when using single card training:
"RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function."
It seems to be the problem of the "Function" Class of Pytorch.
My version of Pytorch is 1.5.0, and I did not make any changes to the code.
May I ask what went wrong? Thanks very much.

**Comment by zhanghang1989** [comment]
I haven't used 1.5.0. PyTorch 1.4.0 works for me. could you try downgrading the PyTorch?

**Comment by Leslie0115** [comment]
To add, I can run the test successfully, but running train will report this error, the error occurs in "syncbn.DistSyncBatchNorm.dist_syncbatchnorm".

**Comment by ad-min570** [comment]
@.你还要干嘛

------------------ 原始邮件 ------------------


    
        发件人: Hang Zhang  <notifications@github.com>;
    
    
        发送时间: 2020-04-29 11:11:26
    
    
        收件人: zhanghang1989/PyTorch-Encoding  <PyTorch-Encoding@noreply.github.com>; 
    
    
        抄送: Subscribed  <subscribed@noreply.github.com>; 
    
    
        主题: Re: [zhanghang1989/PyTorch-Encoding] RuntimeError: Some elementsmarked as dirty during the forward method were not returned as output. Theinputs that are modified inplace must all be outputs of the Function. (#267)
    

 I haven't used 1.5.0. PyTorch 1.4.0 works for me. could you try downgrading the PyTorch?  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Leslie0115** [comment]
It is indeed a problem caused by the Pytorch version, I used 1. 4. 0 no more errors, thank you for your suggestion!

**Comment by Zhaoguanhua** [comment]
i fix the problem in torch==1.7.0  https://github.com/zhanghang1989/PyTorch-Encoding/issues/328#issuecomment-749549857

**Comment by lush-toner** [comment]
> i fix the problem in torch==1.7.0 [#328 (comment)](https://github.com/zhanghang1989/PyTorch-Encoding/issues/328#issuecomment-749549857)

Hello~

When you change the version of torch, did you change the dockerfile(nvcr.io....) or just using a pip(or conda) inside docker container?
