### ISSUE TITLE
How to visulize the result

### ISSUE THREAD

**Issue by kukby** [zhanghang1989/PyTorch-Encoding#275]
Hello thanks for your job ！！ I have tried you code.but I meet a problem.  How can I get the images result after segmentation.

**Comment by zhanghang1989** [comment]
A quick demo using single-scale:
https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html#quick-demo

For multi-scale, please use `test.py`

**Comment by kukby** [comment]
@zhanghang1989 thanks for your reply,   i try the multi-scale but i don't know where the image result be stored.
use the test.py
kukby@kukby-System-Product-Name:~/PyTorch-Encoding/experiments/segmentation$ python3 test.py --dataset ade20k --model encnet --aux --se-loss --resume /home/kukby/PyTorch-Encoding/experiments/segmentation/runs/ade20k/encnet/resnet50/default/checkpoint.pth.tar --eval --test-val 
Output results
pixAcc: 0.7167, mIoU: 0.2596: 100%|███████| 2000/2000 [1:01:57<00:00,  1.86s/it]
pixAcc: 0.7167, mIoU: 0.2596

**Comment by zhanghang1989** [comment]
Removing the `--eval`, you will get the images output into `outdir` folder.

**Comment by zhanghang1989** [comment]
BTW, your model seems not well trained. What's your experiment setting?

**Comment by kukby** [comment]
I just train 10 epoch to test whether it work. So,the Miou will be low

**Comment by kukby** [comment]
I solve the problem THX !!!

**Comment by kukby** [comment]
@zhanghang1989 When I finish  the test.py, it report one error.  
MultiEvalModule: base_size 520, crop_size 480
100%|█████████████████████████████████████| 2000/2000 [1:01:42<00:00,  1.85s/it]
Traceback (most recent call last):
  File "test.py", line 199, in <module>
    test(args)
  File "test.py", line 182, in test
    print( 'pixAcc: %.4f, mIoU: %.4f' % (pixAcc, mIoU))
UnboundLocalError: local variable 'pixAcc' referenced before assignment
Although  the terminal report this error, it can still complete the multi-scale

**Comment by zhanghang1989** [comment]
That's okay. It is the last line of the code. The images should already be generated in `outdir`
