### ISSUE TITLE
train_dist very slow at the beginning of each epoch

### ISSUE THREAD

**Issue by hzhupku** [zhanghang1989/PyTorch-Encoding#280]
I use command: python train_dist.py --dataset ADE20K --model deeplab --aux --backbone resnest200 --epochs 180. And it is really slow at the beginning of each epoch. And I compare it with normal train.py, which performs normally. Though as for overall speed, train_dist is faster, but I believe it could be furthermore.

**Comment by zhanghang1989** [comment]
It may be because of using JIT.

**Comment by hellohwang** [comment]
Hi, have you ever met the eroor when using train_dist.py, could you tell me how to solve it! Please!
_pickle.PicklingError: Can't pickle <function main_worker at 0x7f465ede04c0>: attribute lookup main_worker on main failed.
@hzhupku
