### ISSUE TITLE
Resnet model download may have some minor problems

### ISSUE THREAD

**Issue by Gmgge** [zhanghang1989/PyTorch-Encoding#291]
in code encoding/models/resnet/78line
 return download(model_urls[name],
                        path=root,
                        overwrite=True)
the **overwrite=True**  Make each model load from the Internet instead of local cache
If it’s possible that I set something wrong, I’m sorry to bother you

**Comment by zhanghang1989** [comment]
I think it should be okay to set `overwrite=False`
