### ISSUE TITLE
``import encoding`` at first is too slow.

### ISSUE THREAD

**Issue by Heonjin** [zhanghang1989/PyTorch-Encoding#302]
I have a slow network connection, outbound/inbound 1mb/sec. I fortunately downloaded ``pip install torch-encoding --pre`` and I run a demo code [here](https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html#quick-demo). I just typed ``import encoding`` and it's too slow(still not finished yet). It's been 5 hrs+. I wonder why this is too slow, where the bottle-neck is and if it(importing encoding module) needs the network connection

**Comment by zhanghang1989** [comment]
This doesn't sound right. The `import encoding` should only take 1~2 mins for the first time and it will be very fast next time.

**Comment by Heonjin** [comment]
I stopped the ``import encoding`` and it says like the below. What do you think is the problem?
![image](https://user-images.githubusercontent.com/50353282/88882874-c6650980-d26d-11ea-8ad3-da2fcda89576.png)

**Comment by Heonjin** [comment]
I solved this problem by doing upgrade the version of torch==1.4.0 and torchvision==0.5.0 and then install the torch-encoding.

**Comment by zhanghang1989** [comment]
FYI, the new version should be compatible with pytorch 1.6 https://github.com/zhanghang1989/PyTorch-Encoding/pull/309
