### ISSUE TITLE
Calculating batch_pix_accuracy and batch_intersection_union

### ISSUE THREAD

**Issue by Heonjin** [zhanghang1989/PyTorch-Encoding#306]
In your training [code](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/train.py#L228) of segmentation, ``batch_pix_accuracy`` and ``batch_intersection_union`` are calculated with image size 480 x 480. Is this an accurate calculation of metrics? or should it be fully up-sampled first(into the size of original images) and calculated afterwards? I'm not familiar with semantic segmentation.

**Comment by zhanghang1989** [comment]
Please read the documentation carefully https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html

![image](https://user-images.githubusercontent.com/8041160/89182842-3532b300-d54b-11ea-851d-c0f80a0f7e6e.png)
