### ISSUE TITLE
Support of PyTorch 1.5 and 1.6

### ISSUE THREAD

**Issue by hubertlee915** [zhanghang1989/PyTorch-Encoding#307]
I failed to compile [https://github.com/zhanghang1989/PyTorch-Encoding/tree/master/encoding/lib](url) with PyTorch 1.5 or 1.6. Is there any plan to support latest version of PyTorch?

**Comment by zhanghang1989** [comment]
Sorry that the code does not work for pytorch 1.5 or 1.6. I don't have time to update the code recently. 

I would recommend using the docker:
```
bash scripts/build_docker.sh
bash scripts/run_docker.sh
```

**Comment by hubertlee915** [comment]
Thank you for your reply!

**Comment by zhanghang1989** [comment]
FYI, the new version should be compatible with pytorch 1.6 https://github.com/zhanghang1989/PyTorch-Encoding/pull/309
