### ISSUE TITLE
problem when complie

### ISSUE THREAD

**Issue by guanqj932** [zhanghang1989/PyTorch-Encoding#31]
Hi, hang,
when I compile the code, it shows the following error. Could you help to check where is wrong?

![a615afa291515141a1c94502b0d68ac](https://user-images.githubusercontent.com/32131227/38158289-3b5ec45a-34dd-11e8-8ed5-ef3ce73d5476.png)

**Comment by ksnzh** [comment]
I have the same problem with python3.5.

**Comment by ksnzh** [comment]
Update: Use the solution following #24 and it worked.

**Comment by guanqj932** [comment]
I follow the instruction in #24 ， the compile succeed, but it is wrong when I import encoding in python. It shows that No module named "encoding._ext.encoding_lib._endoding_lib"

**Comment by zhanghang1989** [comment]
Hi @guanqj932 , I guess you are in the package folder. Please retry importing in other folders.

**Comment by guanqj932** [comment]
@zhanghang1989  Yeah， thank you. 
In your docs,  .../encoding.py, 
layer = encoding.Encoding(C,K).double().cuda() ,
I think it should be layer = encoding.nn.Encoding(C,K).double().cuda()

**Comment by ksnzh** [comment]
@zhanghang1989 
import errors
```
ipython
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import encoding
  File "/home/kenzhang/miniconda2/lib/python2.7/site-packages/encoding/parallel.py", line 106
    Hang Zhang, Kristin Dana, Jianping Shi, Zhongyue Zhang, Xiaogang Wang, Ambrish Tyagi, Amit Agrawal. “Context Encoding for Semantic Segmentation. CVPR 2018
                                                                                                                                                              ^
SyntaxError: Non-ASCII character '\xe2' in file /home/kenzhang/miniconda2/lib/python2.7/site-packages/encoding/parallel.py on line 107, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
