### ISSUE TITLE
Missing resnet50 in model_store?

### ISSUE THREAD

**Issue by Minotaur-CN** [zhanghang1989/PyTorch-Encoding#322]
Hi, zhanghang,

I saw the resnet50 model URL is missing in model_store, How can i get this pre-trained model?
Or update the resnet50 by resnest50?

PyTorch-Encoding/encoding/models/model_store.py

[https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/models/model_store.py](url)

`# resnest
    ('fb9de5b360976e3e8bd3679d3e93c5409a5eff3c', 'resnest50'),
    ('966fb78c22323b0c68097c5c1242bd16d3e07fd5', 'resnest101'),
    ('d7fd712f5a1fcee5b3ce176026fbb6d0d278454a', 'resnest200'),
    ('51ae5f19032e22af4ec08e695496547acdba5ce5', 'resnest269'),
    # rectified	
    #('9b5dc32b3b36ca1a6b41ecd4906830fc84dae8ed', 'resnet101_rt'),
    # resnet other variants
    ('a75c83cfc89a56a4e8ba71b14f1ec67e923787b3', 'resnet50s'),
    ('03a0f310d6447880f1b22a83bd7d1aa7fc702c6e', 'resnet101s'),
    ('36670e8bc2428ecd5b7db1578538e2dd23872813', 'resnet152s'),`

**Comment by zhanghang1989** [comment]
`resnet50` has been renamed to `resnet50s`
