### ISSUE TITLE
How can I use code in the encoding folder of the repository instead of the pre-build encoding package

### ISSUE THREAD

**Issue by HaoIrving** [zhanghang1989/PyTorch-Encoding#335]
I am adding a new dataset to the repo, and modified some code in the encoding folder, but they can't be called since this line `from encoding.datasets import get_dataset` in the segmentation/train.py. The previously setuped package is called every time. How can I use code in the encoding folder of the repository instead of the pre-build encoding package? Thanks a lot!

**Comment by zhanghang1989** [comment]
`pip uninstall -y torch-encoding` will uninstall the previous version.

Then follow the ``install from source`` instructions at https://hangzhang.org/PyTorch-Encoding/notes/compile.html#installation

**Comment by HaoIrving** [comment]
Thanks for your reply. I found it can be quickly reinstalled only using `python setup.py install` without previously uninstalling.
