### ISSUE TITLE
Failed downloading url

### ISSUE THREAD

**Issue by sundongwei** [zhanghang1989/PyTorch-Encoding#353]
Dear, Dr.zhang hang, i modify your code ,but can not download pretrained models
![image](https://user-images.githubusercontent.com/30918654/102009947-c9244f00-3d75-11eb-8d5b-4a746c554b5c.png)
![image](https://user-images.githubusercontent.com/30918654/102009974-012b9200-3d76-11eb-922b-5df32fc3b105.png)

**Comment by yangxu351** [comment]
Does it solved?
