### ISSUE TITLE
Why not sent tensor to CUDA?

### ISSUE THREAD

**Issue by BrandonHanx** [zhanghang1989/PyTorch-Encoding#360]
Hi, @zhanghang1989 

Thanks for your work. I wonder why not sent `image `and `target `to gpu like:
`image = image.cuda()` or `image = image.to(device)` ? I cannot figure out when you did this.

https://github.com/zhanghang1989/PyTorch-Encoding/blob/ced288d6fa10d4780fa5205a2f239c84022e71a3/experiments/segmentation/train.py#L199

**Comment by zhanghang1989** [comment]
It is handled in dataparallel.

**Comment by BrandonHanx** [comment]
I see. Thanks for your reply.
