### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Tensor' and 'tuple'

### ISSUE THREAD

**Issue by BrandonHanx** [zhanghang1989/PyTorch-Encoding#361]
Hi, @zhanghang1989 

I encountered some bugs when using `DataParallelModel `and `DataParallelCriterion`.
The error message is as the title.
I wrote a toy snippet to simplify this problem:
`export CUDA_VISIBLE_DEVICES=0,1,2,3`
```python
import torch
import encoding

model = torch.nn.Conv2d(3, 3, 1)
model = encoding.parallel.DataParallelModel(model).cuda()

criterion = torch.nn.BCEWithLogitsLoss()
criterion = encoding.parallel.DataParallelCriterion(criterion).cuda()

input = torch.rand(4, 3, 16, 16).cuda()
label = torch.rand(4, 3, 16, 16).cuda()
output = model(input)
loss = criterion(output, label)
print(loss)
```
The traceback is bellow:
```
Traceback (most recent call last):
  File "tmp.py", line 13, in <module>
    loss = criterion(output, label)
  File "/home/hanxiao/miniconda3/envs/DFF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hanxiao/miniconda3/envs/DFF/lib/python3.8/site-packages/encoding/parallel.py", line 132, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/home/hanxiao/miniconda3/envs/DFF/lib/python3.8/site-packages/encoding/parallel.py", line 185, in _criterion_parallel_apply
    raise output
  File "/home/hanxiao/miniconda3/envs/DFF/lib/python3.8/site-packages/encoding/parallel.py", line 160, in _worker
    output = module(*(input + target), **kwargs)
TypeError: unsupported operand type(s) for +: 'Tensor' and 'tuple'
```

My environment is:
- Ubuntu 18.04
- CUDA 10.1
- Python 3.8
- PyTorch 1.6.0+cu101
- encoding 1.2.2

I would appreciate it if any help received!

**Comment by zhanghang1989** [comment]
If you're using BCELoss, the output channel and label should be 1.

In your case, you may use SoftmaxCELoss.

**Comment by BrandonHanx** [comment]
Thanks so much for your help! 
I did not realize this is due to my improper loss function ...

**Comment by BrandonHanx** [comment]
Well, I admit my loss function does have some problems.

I found above snippet (change BCELoss to BCEWithLogitsLoss) will work correctly when the visible CUDA device is one.

Regardless the exact meaning of loss function, we can conclude that this bug is from DataParallel, right?

**Comment by BrandonHanx** [comment]
Hi, @zhanghang1989 

I found the problem is in this block:
https://github.com/zhanghang1989/PyTorch-Encoding/blob/ced288d6fa10d4780fa5205a2f239c84022e71a3/encoding/parallel.py#L153-L165

Changing the line 160 into `output = module(*(input, target[0]), **kwargs) ` works fine to me.

Does this change make sense?

**Comment by zhanghang1989** [comment]
Feel free to adapt the code for your own purpose. 

The original code was designed for saving memory for multi-gpu training (long-time ago). However, I recommend using Distributed Data Parallel (DDP) now.

**Comment by BrandonHanx** [comment]
I see. Thanks for your advice. 😄
