### ISSUE TITLE
Runtime Error: "ScaledL2_Forward_CUDA" not implemented for 'Half'

### ISSUE THREAD

**Issue by gody7334** [zhanghang1989/PyTorch-Encoding#363]
I train the EncNet using Fastai,
It OK witout mix percision training,
when I add learn().to_fp16(),
it give me this error,

Runtime Error: "ScaledL2_Forward_CUDA" not implemented for 'Half'

I saw pytorch apex lib just add modules into fp32 list,
Any suggestion to add Hlaf to customed cuda operation? 

Thanks.

**Comment by zhanghang1989** [comment]
You may use this pure python implementation https://github.com/open-mmlab/mmsegmentation/blob/9f071cade8cdc59c13b416c7c9843005410c055c/mmseg/ops/encoding.py#L6

**Comment by gody7334** [comment]
Thanks :+1:

**Comment by gody7334** [comment]
Resolved
