### ISSUE TITLE
How to improve performance of PSPNet on cityspaces dataset

### ISSUE THREAD

**Issue by cydqc** [zhanghang1989/PyTorch-Encoding#364]
Hello, @zhanghang1989.

I try to train PSPNet on cityspaces by script " CUDA_VISIBLE_DEVICES=0,1 python train.py --dataset citys --model psp --aux "  with resnet50 as backbone.
However, the model only get 68% miou (PSPNet could achieve 79% moiu in its paper with resnet101). How can i to modify parameters to improve performance. Or do you have any tricks to train PSPNet?

您好，在cityspaces数据集上，我用没改结构的resnet50训练PSPNet只能达到68%的miou，和PSP原文中resnet101的差距有点大，想请教您问题出在哪儿，该如何修改呢。

**Comment by zhanghang1989** [comment]
在 cityscapes上resolution 要加大，建议用 mmsegmentation，他们现在做的很不错

https://github.com/open-mmlab/mmsegmentation

**Comment by zhanghang1989** [comment]
如果想自己训练，建议把 base_size 设置成 1024，crop_size 设成 768，应该能达到接近于原paper水平

**Comment by cydqc** [comment]
> 如果想自己训练，建议把 base_size 设置成 1024，crop_size 设成 768，应该能达到接近于原paper水平

**Comment by cydqc** [comment]
> > 如果想自己训练，建议把 base_size 设置成 1024，crop_size 设成 768，应该能达到接近于原paper水平

**Comment by cydqc** [comment]
3Q！It works

**Comment by June-Jo** [comment]
> 3Q！It works

Could you let me know how long did you take to train pspnet? Time or epoch whichever you know.
