### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by OasisYang** [zhanghang1989/PyTorch-Encoding#38]
Hi, hang,
I follow the instruction on http://hangzh.com/PyTorch-Encoding/notes/compile.html. But it shows the following error when I run "python setup.py install". Could you help to check where is wrong?
Thanks a lot.

![image](https://user-images.githubusercontent.com/17880031/39034017-5f8cb26c-443a-11e8-8b51-584527821ccd.png)

**Comment by zhanghang1989** [comment]
can you try installing the latest version?

**Comment by OasisYang** [comment]
Thanks so much, it works now.
