### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by shwoo93** [zhanghang1989/PyTorch-Encoding#39]
Hello 

Thanks for your kind code sharing.
I have one problem while using your code.

I defined input variable and encoding layer as below.

X = Variable(torch.cuda.DoubleTensor(B,C,H,W).uniform_(-0.5,0.5), requires_grad=True)
layer = encoding.Encoding(C,K).double().cuda()

However, I receive an error when I attempt to forward the input.

 E = layer(X)
AttributeError: module 'encoding._ext.encoding_lib' has no attribute 'Encoding_Double_scaledl2_forward'

Any suggestions?

Thanks

**Comment by zhanghang1989** [comment]
This looks like a library linking error. I couldn't reproduce this. Could you please let me know the system setup?

**Comment by shwoo93** [comment]
I resolved this issue by reinstalling. Thanks.
