### ISSUE TITLE
questions about parallel.py

### ISSUE THREAD

**Issue by leileilin** [zhanghang1989/PyTorch-Encoding#398]
In that code, you mean that input should be already scatterd.
is it achieved by using what?
Thank you man.

**Comment by zhanghang1989** [comment]
Please see the usage example:
https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/train.py#L170-L171

**Comment by leileilin** [comment]
I've read this code and dataset.base.py, I didn't find the code you said.
Thank u man.
