### ISSUE TITLE
No module named 'encoder.params_model'

### ISSUE THREAD

**Issue by alexhaislip** [zhanghang1989/PyTorch-Encoding#402]
`➜  Real-Time-Voice-Cloning git:(master) ✗ python3 demo_cli.py       

Traceback (most recent call last):
  File "/Users/administrator/Projects/Real-Time-Voice-Cloning/demo_cli.py", line 1, in <module>
    from encoder.params_model import model_embedding_size as speaker_embedding_size
ModuleNotFoundError: No module named 'encoder.params_model'`

**Comment by zhanghang1989** [comment]
This seems not my code. Did you ask in the wrong place?

**Comment by alexhaislip** [comment]
@zhanghang1989 Oh sorry mate!

**Comment by Sarekasasikumar** [comment]
> `➜ Real-Time-Voice-Cloning git:(master) ✗ python3 demo_cli.py
> 
> Traceback (most recent call last): File "/Users/administrator/Projects/Real-Time-Voice-Cloning/demo_cli.py", line 1, in from encoder.params_model import model_embedding_size as speaker_embedding_size ModuleNotFoundError: No module named 'encoder.params_model'`

have you resolved this issue. i am having the same one.
