### ISSUE TITLE
编译enclib_cpu模块时出错

### ISSUE THREAD

**Issue by shinkusuki** [zhanghang1989/PyTorch-Encoding#412]
operator.obj : error LNK2001: 无法解析的外部符号 "void __cdecl CONV_RECTIFY_CPU(class at::Tensor &,class at::Tensor const &,class c10::ArrayRef<__int64>,class c10::ArrayRef<__int64>,class c10::ArrayRef<__int64>,class c10::ArrayRef<__int64>,bool)" (?CONV_RECTIFY_CPU@@YAXAEAVTensor@at@@AEBV12@V?$ArrayRef@_J@c10@@222_N@Z)
build\lib.win-amd64-3.6\enclib_cpu.cp36-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

在使用python setup.py install时，运行到这里就出错了。我大概知道是operator.cpp和operator.h的问题，但是我尝试之后没有改善问题。请问可有大佬知道这里应该如何才能解决

**Comment by shinkusuki** [comment]
我可以找到是operator.h中第82至89行
void CONV_RECTIFY_CPU(
  at::Tensor& output,
  const at::Tensor& input,
  at::IntArrayRef kernel_size,
  at::IntArrayRef stride,
  at::IntArrayRef padding,
  at::IntArrayRef dilation,
  bool avg_mode);
这段代码有问题，但是我无法处理

**Comment by shinkusuki** [comment]
在我重新检查各代码后发现是setup.py里少了一个.cpp文件，加入后正常安装了

**Comment by Ximugengqing** [comment]
> 在我重新检查各代码后发现是setup.py里少了一个.cpp文件，加入后正常安装了

请问少了哪一个cpp文件呢

**Comment by shinkusuki** [comment]
> > 在我重新检查各代码后发现是 setup.py 里少了一个.cpp文件，加入后正常安装了
> 
> 请问少了哪一个cpp文件呢

非常抱歉，这个问题是我在22年复现这篇论文时解决的。现在隔了太久了，我不太记得了。你可以去检查一下setup.py里的相关信息，好像是编译在链接时有相关的文件并没有被使用。

**Comment by Ximugengqing** [comment]
> > > 在我重新检查各代码后发现是 setup.py 里少了一个.cpp文件，加入后正常安装了
> > 
> > 
> > 请问少了哪一个cpp文件呢
> 
> 非常抱歉，这个问题是我在22年复现这篇论文时解决的。现在隔了太久了，我不太记得了。你可以去检查一下setup.py里的相关信息，好像是编译在链接时有相关的文件并没有被使用。

感谢您，目前问题仍没有解决，我无法在任何版本的python用任何版本的torch安装好torch-encoding，非常绝望

**Comment by shinkusuki** [comment]
> > > > 在我重新检查各代码后发现是 setup.py 里少了一个.cpp文件，加入后正常安装了
> > > 
> > > 
> > > 请问少了哪一个cpp文件呢
> > 
> > 
> > 非常抱歉，这个问题是我在22年复现这篇论文时解决的。现在隔了太久了，我不太记得了。你可以去检查一下setup.py里的相关信息，好像是编译在链接时有相关的文件并没有被使用。
> 
> 感谢您，目前问题仍没有解决，我无法在任何版本的python用任何版本的torch安装好torch-encoding，非常绝望

我回忆了一下，有一些可以补充的信息，希望可以帮到你。1、我当时重新安装过与C相关的库，高版本的反而没办法编译成功。我记得是安装了VS Studio 2017中关于WINDOWS KITS的一个库。2、我记得我好像是在setup.py里更改了某些文件的顺序、添加了没有使用的文件的名字，例如.cpp .h .cu 为后缀的文件。好像是更改后才可以成功的编译。
非常遗憾在上个月我因为一些原因不得不重装我的电脑，导致我硬盘中关于这篇论文的一些文件丢失了，否则我可以提供一些文件给你的。

**Comment by shinkusuki** [comment]
> > > > 在我重新检查各代码后发现是 setup.py 里少了一个.cpp文件，加入后正常安装了
> > > 
> > > 
> > > 请问少了哪一个cpp文件呢
> > 
> > 
> > 非常抱歉，这个问题是我在22年复现这篇论文时解决的。现在隔了太久了，我不太记得了。你可以去检查一下setup.py里的相关信息，好像是编译在链接时有相关的文件并没有被使用。
> 
> 感谢您，目前问题仍没有解决，我无法在任何版本的python用任何版本的torch安装好torch-encoding，非常绝望

还有一点是你可以找一下在Python的库的文件夹里找一下这个模块对应的文件夹，可能是编译不完全成功，可能你在那个文件夹解决剩下的编译就可以安装成功了
