### ISSUE TITLE
compile error with pytorch0.4

### ISSUE THREAD

**Issue by BeHappy1** [zhanghang1989/PyTorch-Encoding#48]
Hi Hang:
  When i compile encoding using "python setup.py install" , i got the following error.Could you help me solve it. Is encoding/syncbn compatible with the latest pytorch0.4?
  my environment: pytorch0.4,anaconda3,ubuntu16.04 
 
![el0ipj3bfz ifd qd3ij](https://user-images.githubusercontent.com/26538531/39816633-62c7a36c-53ce-11e8-9ae2-16af68b17e84.png)
![iy1p8 lj 5bm4 c 2kl_u](https://user-images.githubusercontent.com/26538531/39816635-639e16d6-53ce-11e8-9dcc-26f18cb24a7e.png)

**Comment by pkuCactus** [comment]
i got the same error

**Comment by mario98** [comment]
Could be related to https://github.com/zhanghang1989/PyTorch-Encoding/issues/44
Check if `<wherever your library dir is located>/python3.5/site-packages/encoding/_ext` does contain an `__init__.py` and if not, copy if from the directory where you have compiled PyTorch-Encoding
 from. There should be the missing `__init__.py` for the `_ext` folder somewhere.

**Comment by pkuCactus** [comment]
This is compile error that the lib python3.5/site-packages/ do not have encoding  dir, let alone the __init__.py.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: mario98 <notifications@github.com>
发送时间: Thursday, May 10, 2018 1:11:22 AM
收件人: zhanghang1989/PyTorch-Encoding
抄送: pkuCactus; Comment
主题: Re: [zhanghang1989/PyTorch-Encoding] compile error with pytorch0.4 (#48)


Could be related to #44<https://github.com/zhanghang1989/PyTorch-Encoding/issues/44>
Check if <wherever your library dir is located>/python3.5/site-packages/encoding/_ext does contain an __init__.py and if not, copy if from the directory where you have compiled PyTorch-Encoding
from. There should be the missing __init__.py for the _ext folder somewhere.

―

**Comment by pkuCactus** [comment]
Hi @BeHappy1 , have you solved this, i still stuck in it. Could you provide some help? Thanks a lot

**Comment by BeHappy1** [comment]
I had previously compiled the master branch of Pytorch, and now i've changed it to the v0.4.0 version of Pytorch , then compile success.

**Comment by ducha-aiki** [comment]
Any success with master branch?

**Comment by pkuCactus** [comment]
@BeHappy1  Thanks a lot.
