### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by sukhad-app** [zhanghang1989/PyTorch-Encoding#5]
Thanks for the Code. How can I train the network on my own dataset of images ?

**Comment by zhanghang1989** [comment]
Please see the example : http://pytorch.org/docs/master/torchvision/datasets.html#imagefolder

**Comment by zhanghang1989** [comment]
@sukhad-app Please check out our new released code for training Deep TEN on your own dataset http://hangzh.com/PyTorch-Encoding/experiments/texture.html#extending-the-software
