### ISSUE TITLE
Can not pip install torch-encoding

### ISSUE THREAD

**Issue by irfanICMLL** [zhanghang1989/PyTorch-Encoding#57]
my pythoch is 0.40, and when I use pip install torch-encoding, it went wrong like this:

    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    error in torch-encoding setup command: '/tmp/pip-build-lhdbv8pg/torch-encoding/build.py' does not name an existing file

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lhdbv8pg/torch-encoding/

**Comment by zhanghang1989** [comment]
`pip install` is not ready yet. please install from source for now. http://hangzh.com/PyTorch-Encoding/notes/compile.html

**Comment by zhanghang1989** [comment]
Hi @irfanICMLL , please ``try pip install torch-encoding``. It should be working now.

**Comment by lxtGH** [comment]
@zhanghang1989 I met this error
running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  
  ----------------------------------------
  Failed building wheel for torch-encoding
  Running setup.py clean for torch-encoding

**Comment by zhanghang1989** [comment]
If pip install does not work, please install from source following the instruction http://hangzh.com/PyTorch-Encoding/notes/compile.html

**Comment by lxtGH** [comment]
@zhanghang1989  Hi ! I build the model from the source. but meet this error when I try to import encoding
----> 1 import encoding

~/anaconda3/lib/python3.6/site-packages/encoding/__init__.py in <module>()
     11 """An optimized PyTorch package with CUDA backend."""
     12 from .version import __version__
---> 13 from . import nn, functions, dilated, parallel, utils, models, datasets

~/anaconda3/lib/python3.6/site-packages/encoding/nn/__init__.py in <module>()
     10 
     11 """Encoding NN Modules"""
---> 12 from .encoding import *
     13 from .syncbn import *
     14 from .customize import *

~/anaconda3/lib/python3.6/site-packages/encoding/nn/encoding.py in <module>()
     16 from torch.nn.modules.utils import _pair
     17 
---> 18 from ..functions import scaledL2, aggregate
     19 
     20 __all__ = ['Encoding', 'EncodingDrop', 'Inspiration', 'UpsampleConv2d']

~/anaconda3/lib/python3.6/site-packages/encoding/functions/__init__.py in <module>()
      1 """Encoding Autograd Fuctions"""
----> 2 from .encoding import *
      3 from .syncbn import *

~/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py in <module>()
     11 import torch
     12 from torch.autograd import Function, Variable
---> 13 from .. import lib
     14 
     15 __all__ = ['aggregate', 'scaledL2']

ImportError: cannot import name 'lib'

**Comment by lxtGH** [comment]
after I move the lib into the site-packe dir, I met this error. It seems like new version of this repo don't complile the cuda code in the lib diretory.
~/anaconda3/lib/python3.6/site-packages/encoding/lib/__init__.py in <module>()
     10         os.path.join(cpu_path, 'roi_align.cpp'),
     11         os.path.join(cpu_path, 'roi_align_cpu.cpp'),
---> 12     ], build_directory=cpu_path, verbose=False)
     13 
     14 if torch.cuda.is_available():

~/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py in load(name, sources, extra_cflags, extra_cuda_cflags, extra_ldflags, extra_include_paths, build_directory, verbose)
    463     '''
    464 
--> 465     verify_ninja_availability()
    466 
    467     # Allows sources to be a single path or a list of paths.

~/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py in verify_ninja_availability()
    519             subprocess.check_call('ninja --version'.split(), stdout=devnull)
    520         except OSError:
--> 521             raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

**Comment by zhanghang1989** [comment]
Please install ninja 1.8.2 by following the instructions https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.WxYrvFMvzJw

**Comment by zhanghang1989** [comment]
Also make sure you are using the `master` branch of PyTroch.

**Comment by lxtGH** [comment]
@zhanghang1989  Hi ! Thanks for reply.
You mean I must use build the pytorch from source? 
I got the following error after updating ninja1.8.2

RuntimeError: Error building extension 'enclib_cpu': [1/2] c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/home/lxt/anaconda3/include/python3.6m -fPIC -std=c++11 -c /home/lxt/anaconda3/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
FAILED: roi_align_cpu.o 
c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/home/lxt/anaconda3/include/python3.6m -fPIC -std=c++11 -c /home/lxt/anaconda3/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
In file included from /home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ArrayRef.h:18:0,
                 from /home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ScalarType.h:5,
                 from /home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Scalar.h:11,
                 from /home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:6,
                 from /home/lxt/anaconda3/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function ‘at::Tensor ROIAlignForwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, double, int64_t)’:
/home/lxt/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Error.h:281:18: error: expected primary-expression before ‘(’ token

**Comment by zhanghang1989** [comment]
This repo relies on PyTorch master branch v0.5.0 or greater. Please let me know if you still have problem after upgrading PyTorch.

**Comment by lxtGH** [comment]
@zhanghang1989 Hi ! Thanks for reply, but there are some errors in the code 
in pcontext.py, line 24, `from detail import Detail` where is detail from ?
in pascal_voc.py line 64, what is the mask from?
in base.py, line 111, it seems like mxnet array.

**Comment by zhanghang1989** [comment]
Hi @lxtGH It is fixed in this PR https://github.com/zhanghang1989/PyTorch-Encoding/pull/63/files#diff-2aece5704556057c86b3898b03a661d9R35 
Please run `prepare_pcontext.py` again.

**Comment by zhanghang1989** [comment]
Resolving this because pip install is working now. Please try `pip install torch-encoding`

**Comment by lxtGH** [comment]
Hi ! @zhanghang1989  I re-install the encoding but met this error when I import encoding: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaledL2, aggregate
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 13, in <module>
    from .. import lib
ImportError: cannot import name 'lib'

**Comment by zhanghang1989** [comment]
That's wired. Could you check if the cuda devices is available now https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/lib/__init__.py#L14
