### ISSUE TITLE
Has anyone tried this syn bn on segmentation task?

### ISSUE THREAD

**Issue by lxtGH** [zhanghang1989/PyTorch-Encoding#58]
I tried but I found it doesn't improve any performance

**Comment by zhanghang1989** [comment]
Please change the default `momentum` value to probably 0.1

**Comment by zhanghang1989** [comment]
Hi @lxtGH , feel free to checkout released source code for EncNet for correctly using SyncBN http://hangzh.com/PyTorch-Encoding/experiments/segmentation.html

**Comment by zhanghang1989** [comment]
Since the example code of EncNet has been released, I assume this issue has been resolved. Feel free to reopen is you still have the problem.
