### ISSUE TITLE
Do you use model_best.pth.tar as the expreiment result in the paper?

### ISSUE THREAD

**Issue by acgtyrant** [zhanghang1989/PyTorch-Encoding#64]
I find that the the mIoU curve of the model variants is non-monotone, then is the experiment results best or latest? I think it is best, do you think this is the academic practice too? Thank you.

The above translated in Chinese: 我发现 mIoU 训练曲线并非一定会单调上升，那请问您在学术论文报告的实验结果是采用 best 还是 latest 呢？我猜是 best，您认为学术界里的惯例也是如此吗。谢谢！

**Comment by lxtGH** [comment]
@acgtyrant I think is best too, by the way what result you got ?(which dataset)

**Comment by zhanghang1989** [comment]
1. Please note that the validation during the training is just for monitoring the correctness using center crop. For evaluating the model please use:
```
python test.py --model fcn --resume mycheckpoint.pth
```
2. The last iteration checkpoint is typically the best model. Saving a separate `best model` is just for resuming the experiments when training crash (we want to keep another checkpoint for save).

**Comment by acgtyrant** [comment]
@lxtGH I have not tried this project yet.
