### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by sukhad-app** [zhanghang1989/PyTorch-Encoding#7]
When I run python setup.py install , I get the following error :cuda runtime error (30) : unknown error at /pytorch/torch/lib/THC/THCGeneral.c:70  at    'install': TestCommand, in setup.py file

**Comment by zhanghang1989** [comment]
Have you installed PyTorch from source using master branch?
http://hangzh.com/PyTorch-Encoding/notes/compile.html#install-pytorch-encoding

**Comment by sukhad-app** [comment]
yes

**Comment by zhanghang1989** [comment]
Please include the full terminal outputs, so that I can locate the error. Thx

**Comment by sukhad-app** [comment]
![image](https://user-images.githubusercontent.com/16850531/31291562-d7eb5d30-aaed-11e7-95e2-d5f5eb392043.png)

**Comment by sukhad-app** [comment]
![image](https://user-images.githubusercontent.com/16850531/31291601-f3e46540-aaed-11e7-9cbb-57555ea56455.png)
 This is the error which I am facing.

**Comment by zhanghang1989** [comment]
This is not the Error from the package, it is from PyTorch. Please make sure you are using PuTorch master branch.

**Comment by zhanghang1989** [comment]
I am closing it. Feel free to reopen if any get the errors again.
