### ISSUE TITLE
Code Breaks with grad checkpointing

### ISSUE THREAD

**Issue by AssassinCroc** [zhanghang1989/PyTorch-Encoding#76]
File "train.py", line 503, in train
    loss.backward(retain_graph=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/checkpoint.py", line 45, in backward
    torch.autograd.backward(outputs, args)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been fr

**Comment by zhanghang1989** [comment]
I don't think you are using my code. The `train.py` only has 180 lines.

**Comment by AssassinCroc** [comment]
@zhanghang1989  You are correct, I am not using your code. However, have you tested the code with gradient check pointing feature of pytorch https://pytorch.org/docs/stable/checkpoint.html

**Comment by zhanghang1989** [comment]
Yes, I have unitest for all customized operators https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/tests/unit_test/test_module.py

**Comment by zhanghang1989** [comment]
Closing it due to no recent activities. Feel free to reopen.

**Comment by zxbyte** [comment]
> @zhanghang1989 You are correct, I am not using your code. However, have you tested the code with gradient check pointing feature of pytorch https://pytorch.org/docs/stable/checkpoint.html

请问你的问题解决了吗？我在使用torch.utils.checkpoint的时候也遇到了这个RuntimeError: Trying to backward through the graph a second time.....的问题，不使用checkpoint机制就没有问题。

**Comment by zxbyte** [comment]
> @zhanghang1989 You are correct, I am not using your code. However, have you tested the code with gradient check pointing feature of pytorch https://pytorch.org/docs/stable/checkpoint.html

Have you resolved the problem？I have encountered the same problem when i using torch.utils.checkpoint, "RuntimeError: Trying to backward through the graph a second time.....". Do you have any suggestion?
