### ISSUE TITLE
/home/PyTorch-Encoding-Layer-master/encoding/src/encoding_lib.cpp:12:26: fatal error: thc_encoding.h: No such file or directory

### ISSUE THREAD

**Issue by gaopeng-eugene** [zhanghang1989/PyTorch-Encoding#8]

**Comment by gaopeng-eugene** [comment]
Unable to solve this problem

**Comment by zhanghang1989** [comment]
Please follow the installation instructions http://hangzh.com/PyTorch-Encoding/notes/compile.html

**Comment by zhanghang1989** [comment]
Let me know if you still have the problem. Thanks!

**Comment by Tangzy7** [comment]
@zhanghang1989 I have the same problem

**Comment by zhanghang1989** [comment]
First make sure you have installed PyTorch to your $HOME directory http://hangzh.com/PyTorch-Encoding/notes/compile.html#install-pytorch-encoding

Then attached the entire terminal output, if you still have the trouble. Thanks!

**Comment by david2021** [comment]
I have the same issue

**Comment by david2021** [comment]
Actually, before this it has some errors as below:
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00006bd3_00000000-7_thc_encoding.cpp1.ii".
Compilation terminated.
CMake Error at ENCODING_generated_thc_encoding.cu.o.cmake:264 (message):
  Error generating file
  /home/lin1.sun/PyTorch-Encoding/encoding/build/CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o


make[2]: *** [CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o] Error 1
make[1]: *** [CMakeFiles/ENCODING.dir/all] Error 2
make: *** [all] Error 2

**Comment by zhanghang1989** [comment]
Can you attach the entire terminal outputs, so that I can locate the error. Thanks!

**Comment by zhanghang1989** [comment]
See the new commit https://github.com/zhanghang1989/PyTorch-Encoding/commit/c92a7c2422af69b4b0f920b379533319d7bb6f0f
