### ISSUE TITLE
The influence of "align_corners"

### ISSUE THREAD

**Issue by PkuRainBow** [zhanghang1989/PyTorch-Encoding#80]
I noticed a small detail that you set the "align_corners=True" when you upsample the image or  feature map.

But it seems this feature is supported from PytorchV0.4, thus I am wondering the influence of this setting~

**Comment by zhanghang1989** [comment]
align_center=True which was the same behavior as the default setting of PyTorch before 0.3. After 0.4, the default setting has been changed. This influence is subtle when using fix training and evaluation size.

**Comment by PkuRainBow** [comment]
@zhanghang1989 Got it, thanks!
