### ISSUE TITLE
The small issue within "test_batchify_fn"

### ISSUE THREAD

**Issue by PkuRainBow** [zhanghang1989/PyTorch-Encoding#82]
Sorry to bother you again, I find a small issue within the implementation for "encoding/dataset/base.py/test_batchify_fn",

```
def test_batchify_fn(data):
    error_msg = "batch must contain tensors, tuples or lists; found {}"
    if isinstance(data[0], (str, torch.Tensor)):
        return list(data)
    elif isinstance(data[0], (tuple, list)):
        data = zip(*data)
        return [test_batchify_fn(i) for i in data]
    raise TypeError((error_msg.format(type(batch[0]))))

```

It seems that you don't define the **batch** within this function.

**Comment by zhanghang1989** [comment]
It is used here for multisize evaluation: https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/test.py#L47-L49
