### ISSUE TITLE
 The resnet50 and resnet101 model

### ISSUE THREAD

**Issue by wenqingchu** [zhanghang1989/PyTorch-Encoding#84]
Hi, is the provided resnet50 and resnet101 model pretrained on the COCO dataset? 
If not, are you willing to provide those?

**Comment by zhanghang1989** [comment]
The model is not pretrained on COCO. I am happy to provide those in later version.

**Comment by YifuLiuL** [comment]
Hi, I also have the same question. Can you provide resnet101 model pretrained on the COCO dataset?

**Comment by zhanghang1989** [comment]
https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/models/model_store.py#L20
