### ISSUE TITLE
No module named 'detail'

### ISSUE THREAD

**Issue by gshdong** [zhanghang1989/PyTorch-Encoding#87]
When I run the command  'python test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext --eval', an error occur as follows:
```
(py3) dgs@ubuntu-server:PyTorch-Encoding/experiments/segmentation$ python test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext --eval
Traceback (most recent call last):
  File "test.py", line 124, in <module>
    test(args)
  File "test.py", line 40, in test
    transform=input_transform)
  File "/home/dgs/anaconda2/envs/py3/lib/python3.6/site-packages/encoding/datasets/__init__.py", line 15, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)
  File "/home/dgs/anaconda2/envs/py3/lib/python3.6/site-packages/encoding/datasets/pcontext.py", line 24, in __init__
    from detail import Detail
ModuleNotFoundError: No module named 'detail'
```
I hope someone can help me solve this problem, thanks.

**Comment by huangxGo** [comment]
I met the same problem.Could you tell me how to solve this? THANKS! @gshdong

**Comment by gshdong** [comment]
@huangxGo 你得先运行scripts文件夹下的Python文件，比如prepare_pcontext.py，里面包含detail-api的安装。

**Comment by my462** [comment]
The detail api can also be installed manually by downloading from the author's repository.

**Comment by huangxGo** [comment]
Thank you so much ! I install the detail api manually and it works fine! @gshdong @my462

**Comment by zhuizhunew** [comment]
@my462 where to download exactly?can you offer the address?thank you very much!

**Comment by StacyYang** [comment]
https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/scripts/prepare_pcontext.py#L43
