### ISSUE TITLE
Training details for Pascal VOC

### ISSUE THREAD

**Issue by ascust** [zhanghang1989/PyTorch-Encoding#88]
Hi,
Could you provide more details on how to train it on PASCAL VOC 12. For example, do I have to train it first on pascal_aug and fine-tune it on pascal_voc? If so, how do I choose the checkpoint and what are the training parameters? Thank you.

**Comment by my462** [comment]
Also interested in how to pretrain on one dataset and then fine-tune on another.
See the ft option in train.py but don't know how it works.

**Comment by zhanghang1989** [comment]
`--resume path/to/checkpoint.pth --ft` will do the job
