### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by isaykatsman** [zhanghang1989/PyTorch-Encoding#9]
Hello, I was able to install the library but for some reason the `test_dilated_avgpool` test case fails with the error `RuntimeError: there are no graph nodes that require computing gradients`. Is this anticipated?

**Comment by zhanghang1989** [comment]
There is a bug in `DilatedAvgPool2d`. I will fix it in later commit. The other component should be okay to use.

**Comment by zhanghang1989** [comment]
See the new commit https://github.com/zhanghang1989/PyTorch-Encoding/commit/c92a7c2422af69b4b0f920b379533319d7bb6f0f
